<xsl:stylesheet version="1.0" 
		xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
		xmlns:xl="http://www.w3.org/1999/xlink"
		xmlns:tei="http://www.tei-c.org/ns/1.0"
		xmlns="http://www.tei-c.org/ns/1.0"
		>

<!-- @SUMMARY@= Create a header for the project's teiCorpus. -->

<xsl:param name="version" select="1.0"/>
<xsl:param name="project"/>
<xsl:output method="xml" indent="yes" encoding="utf-8"/>

<xsl:template match="/">
  <xsl:param name="datestamp" 
	     select="document('http://oracc.museum.upenn.edu/datestamp')/*"/>
  <teiHeader>
    <fileDesc>
      <titleStmt>
	<title>TEI version of <xsl:value-of select="$project"/> corpus</title>
	<respStmt>
	  <resp>generated by</resp>
	  <name type="program">teicorpus-header.xsl 1.0</name>
	</respStmt>
      </titleStmt>
      <publicationStmt>
	<availability><p>Electronic manuscript</p></availability>
	<date><xsl:value-of select="$datestamp"/></date>
      </publicationStmt>
      <sourceDesc>
	<p>This is the concatenation of all TEI files in the project with additional
	metadata included from the project's glossaries.  Supporting data derived
	from the project glossaries are prepended.</p>
      </sourceDesc>
    </fileDesc>
  </teiHeader>
</xsl:template>

</xsl:stylesheet>
