<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="2.0">
   <xsl:character-map name="iso-8859-1">
      <xsl:output-character character="&#160;" string="&amp;#160;"/>
      <xsl:output-character character="&#161;" string="&amp;#161;"/>
      <xsl:output-character character="&#162;" string="&amp;#162;"/>
      <xsl:output-character character="&#163;" string="&amp;#163;"/>
      <xsl:output-character character="&#164;" string="&amp;#164;"/>
      <xsl:output-character character="&#165;" string="&amp;#165;"/>
      <xsl:output-character character="&#166;" string="&amp;#166;"/>
      <xsl:output-character character="&#167;" string="&amp;#167;"/>
      <xsl:output-character character="&#168;" string="&amp;#168;"/>
      <xsl:output-character character="&#169;" string="&amp;#169;"/>
      <xsl:output-character character="&#170;" string="&amp;#170;"/>
      <xsl:output-character character="&#171;" string="&amp;#171;"/>
      <xsl:output-character character="&#172;" string="&amp;#172;"/>
      <xsl:output-character character="&#173;" string="&amp;#173;"/>
      <xsl:output-character character="&#174;" string="&amp;#174;"/>
      <xsl:output-character character="&#175;" string="&amp;#175;"/>
      <xsl:output-character character="&#176;" string="&amp;#176;"/>
      <xsl:output-character character="&#177;" string="&amp;#177;"/>
      <xsl:output-character character="&#178;" string="&amp;#178;"/>
      <xsl:output-character character="&#179;" string="&amp;#179;"/>
      <xsl:output-character character="&#180;" string="&amp;#180;"/>
      <xsl:output-character character="&#181;" string="&amp;#181;"/>
      <xsl:output-character character="&#182;" string="&amp;#182;"/>
      <xsl:output-character character="&#183;" string="&amp;#183;"/>
      <xsl:output-character character="&#184;" string="&amp;#184;"/>
      <xsl:output-character character="&#185;" string="&amp;#185;"/>
      <xsl:output-character character="&#186;" string="&amp;#186;"/>
      <xsl:output-character character="&#187;" string="&amp;#187;"/>
      <xsl:output-character character="&#188;" string="&amp;#188;"/>
      <xsl:output-character character="&#189;" string="&amp;#189;"/>
      <xsl:output-character character="&#190;" string="&amp;#190;"/>
      <xsl:output-character character="&#191;" string="&amp;#191;"/>
      <xsl:output-character character="&#192;" string="&amp;#192;"/>
      <xsl:output-character character="&#193;" string="&amp;#193;"/>
      <xsl:output-character character="&#194;" string="&amp;#194;"/>
      <xsl:output-character character="&#195;" string="&amp;#195;"/>
      <xsl:output-character character="&#196;" string="&amp;#196;"/>
      <xsl:output-character character="&#197;" string="&amp;#197;"/>
      <xsl:output-character character="&#198;" string="&amp;#198;"/>
      <xsl:output-character character="&#199;" string="&amp;#199;"/>
      <xsl:output-character character="&#200;" string="&amp;#200;"/>
      <xsl:output-character character="&#201;" string="&amp;#201;"/>
      <xsl:output-character character="&#202;" string="&amp;#202;"/>
      <xsl:output-character character="&#203;" string="&amp;#203;"/>
      <xsl:output-character character="&#204;" string="&amp;#204;"/>
      <xsl:output-character character="&#205;" string="&amp;#205;"/>
      <xsl:output-character character="&#206;" string="&amp;#206;"/>
      <xsl:output-character character="&#207;" string="&amp;#207;"/>
      <xsl:output-character character="&#208;" string="&amp;#208;"/>
      <xsl:output-character character="&#209;" string="&amp;#209;"/>
      <xsl:output-character character="&#210;" string="&amp;#210;"/>
      <xsl:output-character character="&#211;" string="&amp;#211;"/>
      <xsl:output-character character="&#212;" string="&amp;#212;"/>
      <xsl:output-character character="&#213;" string="&amp;#213;"/>
      <xsl:output-character character="&#214;" string="&amp;#214;"/>
      <xsl:output-character character="&#215;" string="&amp;#215;"/>
      <xsl:output-character character="&#216;" string="&amp;#216;"/>
      <xsl:output-character character="&#217;" string="&amp;#217;"/>
      <xsl:output-character character="&#218;" string="&amp;#218;"/>
      <xsl:output-character character="&#219;" string="&amp;#219;"/>
      <xsl:output-character character="&#220;" string="&amp;#220;"/>
      <xsl:output-character character="&#221;" string="&amp;#221;"/>
      <xsl:output-character character="&#222;" string="&amp;#222;"/>
      <xsl:output-character character="&#223;" string="&amp;#223;"/>
      <xsl:output-character character="&#224;" string="&amp;#224;"/>
      <xsl:output-character character="&#225;" string="&amp;#225;"/>
      <xsl:output-character character="&#226;" string="&amp;#226;"/>
      <xsl:output-character character="&#227;" string="&amp;#227;"/>
      <xsl:output-character character="&#228;" string="&amp;#228;"/>
      <xsl:output-character character="&#229;" string="&amp;#229;"/>
      <xsl:output-character character="&#230;" string="&amp;#230;"/>
      <xsl:output-character character="&#231;" string="&amp;#231;"/>
      <xsl:output-character character="&#232;" string="&amp;#232;"/>
      <xsl:output-character character="&#233;" string="&amp;#233;"/>
      <xsl:output-character character="&#234;" string="&amp;#234;"/>
      <xsl:output-character character="&#235;" string="&amp;#235;"/>
      <xsl:output-character character="&#236;" string="&amp;#236;"/>
      <xsl:output-character character="&#237;" string="&amp;#237;"/>
      <xsl:output-character character="&#238;" string="&amp;#238;"/>
      <xsl:output-character character="&#239;" string="&amp;#239;"/>
      <xsl:output-character character="&#240;" string="&amp;#240;"/>
      <xsl:output-character character="&#241;" string="&amp;#241;"/>
      <xsl:output-character character="&#242;" string="&amp;#242;"/>
      <xsl:output-character character="&#243;" string="&amp;#243;"/>
      <xsl:output-character character="&#244;" string="&amp;#244;"/>
      <xsl:output-character character="&#245;" string="&amp;#245;"/>
      <xsl:output-character character="&#246;" string="&amp;#246;"/>
      <xsl:output-character character="&#247;" string="&amp;#247;"/>
      <xsl:output-character character="&#248;" string="&amp;#248;"/>
      <xsl:output-character character="&#249;" string="&amp;#249;"/>
      <xsl:output-character character="&#250;" string="&amp;#250;"/>
      <xsl:output-character character="&#251;" string="&amp;#251;"/>
      <xsl:output-character character="&#252;" string="&amp;#252;"/>
      <xsl:output-character character="&#253;" string="&amp;#253;"/>
      <xsl:output-character character="&#254;" string="&amp;#254;"/>
      <xsl:output-character character="&#255;" string="&amp;#255;"/>
   </xsl:character-map>
</xsl:stylesheet>