#line 2 "cbd-l.c"

#line 4 "cbd-l.c"

#define YY_NO_INPUT 1
#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

/* %not-for-header */
/* %if-c-only */
/* %if-not-reentrant */
#define yy_create_buffer cbd_create_buffer
#define yy_delete_buffer cbd_delete_buffer
#define yy_scan_buffer cbd_scan_buffer
#define yy_scan_string cbd_scan_string
#define yy_scan_bytes cbd_scan_bytes
#define yy_init_buffer cbd_init_buffer
#define yy_flush_buffer cbd_flush_buffer
#define yy_load_buffer_state cbd_load_buffer_state
#define yy_switch_to_buffer cbd_switch_to_buffer
#define yypush_buffer_state cbdpush_buffer_state
#define yypop_buffer_state cbdpop_buffer_state
#define yyensure_buffer_stack cbdensure_buffer_stack
#define yy_flex_debug cbd_flex_debug
#define yyin cbdin
#define yyleng cbdleng
#define yylex cbdlex
#define yylineno cbdlineno
#define yyout cbdout
#define yyrestart cbdrestart
#define yytext cbdtext
#define yywrap cbdwrap
#define yyalloc cbdalloc
#define yyrealloc cbdrealloc
#define yyfree cbdfree

/* %endif */
/* %endif */
/* %ok-for-header */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* %if-c++-only */
/* %endif */

/* %if-c-only */
#ifdef yy_create_buffer
#define cbd_create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer cbd_create_buffer
#endif

#ifdef yy_delete_buffer
#define cbd_delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer cbd_delete_buffer
#endif

#ifdef yy_scan_buffer
#define cbd_scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer cbd_scan_buffer
#endif

#ifdef yy_scan_string
#define cbd_scan_string_ALREADY_DEFINED
#else
#define yy_scan_string cbd_scan_string
#endif

#ifdef yy_scan_bytes
#define cbd_scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes cbd_scan_bytes
#endif

#ifdef yy_init_buffer
#define cbd_init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer cbd_init_buffer
#endif

#ifdef yy_flush_buffer
#define cbd_flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer cbd_flush_buffer
#endif

#ifdef yy_load_buffer_state
#define cbd_load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state cbd_load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define cbd_switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer cbd_switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define cbdpush_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state cbdpush_buffer_state
#endif

#ifdef yypop_buffer_state
#define cbdpop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state cbdpop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define cbdensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack cbdensure_buffer_stack
#endif

#ifdef yylex
#define cbdlex_ALREADY_DEFINED
#else
#define yylex cbdlex
#endif

#ifdef yyrestart
#define cbdrestart_ALREADY_DEFINED
#else
#define yyrestart cbdrestart
#endif

#ifdef yylex_init
#define cbdlex_init_ALREADY_DEFINED
#else
#define yylex_init cbdlex_init
#endif

#ifdef yylex_init_extra
#define cbdlex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra cbdlex_init_extra
#endif

#ifdef yylex_destroy
#define cbdlex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy cbdlex_destroy
#endif

#ifdef yyget_debug
#define cbdget_debug_ALREADY_DEFINED
#else
#define yyget_debug cbdget_debug
#endif

#ifdef yyset_debug
#define cbdset_debug_ALREADY_DEFINED
#else
#define yyset_debug cbdset_debug
#endif

#ifdef yyget_extra
#define cbdget_extra_ALREADY_DEFINED
#else
#define yyget_extra cbdget_extra
#endif

#ifdef yyset_extra
#define cbdset_extra_ALREADY_DEFINED
#else
#define yyset_extra cbdset_extra
#endif

#ifdef yyget_in
#define cbdget_in_ALREADY_DEFINED
#else
#define yyget_in cbdget_in
#endif

#ifdef yyset_in
#define cbdset_in_ALREADY_DEFINED
#else
#define yyset_in cbdset_in
#endif

#ifdef yyget_out
#define cbdget_out_ALREADY_DEFINED
#else
#define yyget_out cbdget_out
#endif

#ifdef yyset_out
#define cbdset_out_ALREADY_DEFINED
#else
#define yyset_out cbdset_out
#endif

#ifdef yyget_leng
#define cbdget_leng_ALREADY_DEFINED
#else
#define yyget_leng cbdget_leng
#endif

#ifdef yyget_text
#define cbdget_text_ALREADY_DEFINED
#else
#define yyget_text cbdget_text
#endif

#ifdef yyget_lineno
#define cbdget_lineno_ALREADY_DEFINED
#else
#define yyget_lineno cbdget_lineno
#endif

#ifdef yyset_lineno
#define cbdset_lineno_ALREADY_DEFINED
#else
#define yyset_lineno cbdset_lineno
#endif

#ifdef yywrap
#define cbdwrap_ALREADY_DEFINED
#else
#define yywrap cbdwrap
#endif

/* %endif */

#ifdef yyalloc
#define cbdalloc_ALREADY_DEFINED
#else
#define yyalloc cbdalloc
#endif

#ifdef yyrealloc
#define cbdrealloc_ALREADY_DEFINED
#else
#define yyrealloc cbdrealloc
#endif

#ifdef yyfree
#define cbdfree_ALREADY_DEFINED
#else
#define yyfree cbdfree
#endif

/* %if-c-only */

#ifdef yytext
#define cbdtext_ALREADY_DEFINED
#else
#define yytext cbdtext
#endif

#ifdef yyleng
#define cbdleng_ALREADY_DEFINED
#else
#define yyleng cbdleng
#endif

#ifdef yyin
#define cbdin_ALREADY_DEFINED
#else
#define yyin cbdin
#endif

#ifdef yyout
#define cbdout_ALREADY_DEFINED
#else
#define yyout cbdout
#endif

#ifdef yy_flex_debug
#define cbd_flex_debug_ALREADY_DEFINED
#else
#define yy_flex_debug cbd_flex_debug
#endif

#ifdef yylineno
#define cbdlineno_ALREADY_DEFINED
#else
#define yylineno cbdlineno
#endif

/* %endif */

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
/* %if-c-only */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>
/* %endif */

/* %if-tables-serialization */
/* %endif */
/* end standard C headers. */

/* %if-c-or-c++ */
/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* %endif */

/* begin standard C++ headers. */
/* %if-c++-only */
/* %endif */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* %not-for-header */
/* Returned upon end-of-file. */
#define YY_NULL 0
/* %ok-for-header */

/* %not-for-header */
/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))
/* %ok-for-header */

/* %if-reentrant */
/* %endif */

/* %if-not-reentrant */

/* %endif */

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

/* %if-not-reentrant */
extern int yyleng;
/* %endif */

/* %if-c-only */
/* %if-not-reentrant */
extern FILE *yyin, *yyout;
/* %endif */
/* %endif */

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
/* %if-c-only */
	FILE *yy_input_file;
/* %endif */

/* %if-c++-only */
/* %endif */

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */
/* %if-not-reentrant */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */
/* %endif */
/* %ok-for-header */

/* %endif */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* %if-c-only Standard (non-C++) definition */

/* %if-not-reentrant */
/* %not-for-header */
/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;
/* %ok-for-header */

/* %endif */

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

/* %endif */

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* %% [1.0] yytext/yyin/yyout/yy_state_type/yylineno etc. def's & init go here */
/* Begin user sect3 */

#define cbdwrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

#define FLEX_DEBUG
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

/* %% [1.5] DFA */

/* %if-c-only Standard (non-C++) definition */

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* %endif */

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
/* %% [2.0] code to fiddle yytext and yyleng for yymore() goes here \ */\
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
/* %% [3.0] code to copy yytext_ptr to yytext[] goes here, if %array \ */\
	(yy_c_buf_p) = yy_cp;
/* %% [4.0] data tables for the DFA and the user's section 1 definitions go here */
#define YY_NUM_RULES 48
#define YY_END_OF_BUFFER 49
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_acclist[175] =
    {   0,
       47,   47,   49,   48,   11,   48,   12,   48,    1,   48,
        3,   48,   48,   26,   48,   28,   48,   48,   17,   48,
       25,   48,   18,   48,   20,   48,   37,   48,   37,   39,
       48,   48,   48,   48,   37,   48,   48,   48,   48,   37,
       48,    8,   48,   47,   48,   19,   48,   19,   25,   48,
       24,   48,   46,   48,   22,   48,   25,   48,   23,   48,
       48,   43,   48,   44,   48,   43,   48,   43,   48,   15,
       48,   13,   48,   14,   48,   11,    3,    2,    9,    6,
    16391,    6,16391,    6,16391,   26,   28,   27,   16,   25,
       37,   37,   37,   39,   38,   35,   35,   33,   29,   37,

       36,   32,   31,   30,   37,    8,   47,   19,   19,   25,
       46,   22,   22,   21,   25,   23,   10,   43,   43,   44,
       40,   43,   42,   43,   42,   43,   15,   13,   14,    2,
     8199,    6,16391,    6,16391,   35,   34,   35,   33,   29,
       37,   36,   32,   31,   30,   37,   40,   43,   42,   43,
       41,   42,   43,    6,16391,    6,16391,   34,   35,   41,
       42,   43,    6,16391,    6,16391,    6,16391,    6,   45,
    16391,   45,    4,    5
    } ;

static const flex_int16_t yy_accept[155] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    4,    5,    7,
        9,   11,   13,   14,   16,   18,   19,   21,   23,   25,
       27,   29,   32,   33,   34,   35,   37,   38,   39,   40,
       42,   44,   46,   48,   51,   53,   55,   57,   59,   61,
       62,   64,   66,   68,   70,   72,   74,   76,   77,   78,
       79,   80,   82,   84,   86,   87,   88,   89,   90,   90,
       91,   92,   93,   95,   96,   97,   98,   99,  101,  102,
      103,  104,  106,  107,  108,  109,  111,  112,  113,  114,

      115,  116,  117,  118,  119,  120,  121,  123,  125,  127,
      128,  129,  130,  131,  132,  134,  136,  137,  139,  140,
      142,  143,  144,  145,  147,  149,  151,  154,  156,  158,
      160,  163,  163,  165,  165,  165,  167,  167,  167,  169,
      169,  169,  172,  172,  172,  173,  173,  173,  173,  174,
      174,  174,  175,  175
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    1,    5,    6,    7,    1,    1,    1,
        1,    8,    9,    1,   10,   11,   12,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,   13,    1,   14,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       16,    1,   17,    1,    1,    1,   18,   18,   19,   20,

       21,   18,   18,   18,   22,   18,   18,   23,   18,   24,
       18,   18,   18,   25,   26,   27,   28,   18,   18,   18,
       29,   18,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[30] =
    {   0,
        1,    2,    3,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    4,    5,    6,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7
    } ;

static const flex_int16_t yy_base[188] =
    {   0,
        0,    2,    4,    6,   11,   15,   31,   44,   15,   16,
      388,  387,   27,   52,   19,   23,   39,   57,  375,  374,
       68,   83,  384,  383,   59,   61,  385,  392,  382,  392,
      392,   55,   59,    0,  381,  368,  379,  378,  392,  392,
      377,  376,  363,  371,    0,  373,    0,    0,    0,  372,
       68,    0,    0,  371,  392,    0,   63,   75,  392,    0,
      370,  369,  368,   65,    0,    0,  367,  366,  365,  364,
      350,   83,  340,  339,    0,  360,  392,  359,  358,  357,
      356,  355,  354,  392,  353,  352,  351,  350,  349,  348,
      343,  336,   85,    0,    0,  329,    0,   93,   98,  392,

      100,  392,    0,  328,  322,  315,  308,   90,  301,    0,
        0,  287,  286,  100,  265,  263,  273,  266,  259,  258,
      252,  251,  245,  244,  238,  231,  230,  224,  202,  217,
      213,   95,  186,  188,  184,  184,  174,  176,   99,   94,
       92,  115,   86,   62,   46,  103,    9,  107,  392,  109,
      111,  392,  392,  121,  128,  135,  142,  149,  156,  163,
      170,  177,  184,  191,  195,  202,  209,  216,  223,  230,
      237,  244,  251,  258,  265,  272,  279,  286,  293,    3,
      300,  307,  314,  321,  328,  335,  342
    } ;

static const flex_int16_t yy_def[188] =
    {   0,
      154,  154,  155,  155,  156,  156,  157,  157,  154,  154,
      158,  158,  159,  159,  160,  160,  161,  161,  154,  154,
      162,  162,  163,  163,  164,  164,  153,  153,  153,  153,
      153,  153,  165,  166,  153,  153,  167,  153,  153,  153,
      168,  168,  153,  169,  170,  171,  172,  173,  174,  175,
      153,  176,  177,  177,  153,  178,  179,  153,  153,  180,
      181,  153,  182,  183,  184,  185,  153,  153,  153,  153,
      153,  165,   72,   72,  166,  153,  153,  167,  167,  153,
      168,  153,  153,  153,  169,  186,  170,  171,  172,  173,
      174,  175,  153,  176,  177,  177,  178,  179,  153,  153,

      153,  153,  180,  181,  153,  153,  182,  183,  187,  184,
      185,  153,  153,  153,   72,   72,  153,  186,  153,  153,
      153,  153,  153,  153,  153,  153,  187,   72,   72,  153,
      153,  153,   72,  153,  153,   72,  153,  153,   72,  153,
      153,   72,  153,  153,  153,  153,  153,  153,  153,  153,
      153,  153,    0,  153,  153,  153,  153,  153,  153,  153,
      153,  153,  153,  153,  153,  153,  153,  153,  153,  153,
      153,  153,  153,  153,  153,  153,  153,  153,  153,  153,
      153,  153,  153,  153,  153,  153,  153
    } ;

static const flex_int16_t yy_nxt[422] =
    {   0,
      153,   29,   30,   29,   30,   35,   36,   35,   36,  103,
       31,   31,   38,   28,   32,   33,   38,   28,   51,   51,
       28,   28,   51,   51,   28,   28,   39,   40,   54,   55,
       39,   40,   42,   43,  150,   44,   45,   46,   47,   48,
       58,   59,   49,   40,   50,   42,   43,  145,   44,   45,
       46,   47,   48,   54,   55,   49,   69,   50,   58,   59,
       67,   28,   67,   28,   99,  100,  105,   70,   40,   62,
       28,   93,   63,   71,   63,   93,  101,  102,   63,   73,
       74,  109,  147,   64,   62,   28,  114,   63,   93,   63,
      114,  126,   93,   63,   99,  100,  132,  153,   64,   99,

      100,  101,  102,  114,  148,  149,  127,  114,  148,  149,
      151,  152,  151,  152,  146,  134,  145,  144,  143,  142,
      135,   28,   28,   28,   28,   28,   28,   28,   34,   34,
       34,   34,   34,   34,   34,   37,   37,   37,   37,   37,
       37,   37,   41,   41,   41,   41,   41,   41,   41,   52,
       52,   52,   52,   52,   52,   52,   53,   53,   53,   53,
       53,   53,   53,   56,   56,   56,   56,   56,   56,   56,
       57,   57,   57,   57,   57,   57,   57,   61,   61,   61,
       61,   61,   61,   61,   65,   65,   65,   65,   65,   65,
       65,   66,   66,   66,   66,   66,   66,   66,   72,  141,

      140,   72,   75,  139,  138,   75,   75,   75,   75,   78,
       78,  137,   78,  136,  131,   78,   81,   81,  130,   81,
       81,   81,   81,   85,  133,  132,   85,   85,   85,   85,
       87,  131,  126,   87,   87,   87,   87,   88,   88,  125,
       88,   88,   88,   88,   89,  124,  123,   89,   89,   89,
       89,   90,  122,  121,   90,   90,   90,   90,   91,  120,
      119,   91,   91,   91,   91,   92,   92,  130,   92,   92,
       92,   92,   94,   94,  117,   94,   94,   94,   94,   95,
       95,  129,   95,   95,  128,   95,   97,  113,  112,   97,
       97,   97,   97,   98,   98,   98,   98,   98,   98,   98,

      104,  104,  126,  104,  104,  104,  104,  107,  107,  125,
      107,  107,  107,  107,  108,  108,  106,  108,  108,  108,
      108,  110,  110,  105,  110,  110,  110,  110,  111,  105,
       96,  111,  111,  111,  111,  118,  118,  124,  118,  118,
      118,  118,  109,  109,  123,  109,  109,  109,  109,  122,
      121,  120,  119,  117,  117,   83,   82,   82,   80,   79,
       79,   76,  116,  115,   71,  113,   69,   68,  112,  105,
      106,  105,   96,   82,   82,   86,   84,   83,   82,   80,
       79,   77,   76,   68,  153,   28,   28,   60,   60,   28,
       28,   27,  153,  153,  153,  153,  153,  153,  153,  153,

      153,  153,  153,  153,  153,  153,  153,  153,  153,  153,
      153,  153,  153,  153,  153,  153,  153,  153,  153,  153,
      153
    } ;

static const flex_int16_t yy_chk[422] =
    {   0,
        0,    1,    1,    2,    2,    3,    3,    4,    4,  180,
        2,    2,    5,    5,    2,    2,    6,    6,    9,   10,
       15,   15,    9,   10,   16,   16,    5,    5,   13,   13,
        6,    6,    7,    7,  147,    7,    7,    7,    7,    7,
       17,   17,    7,   13,    7,    8,    8,  145,    8,    8,
        8,    8,    8,   14,   14,    8,   32,    8,   18,   18,
       25,   25,   26,   26,   57,   57,   64,   32,   14,   21,
       21,   51,   21,   33,   21,   51,   58,   58,   21,   33,
       33,   64,  144,   21,   22,   22,   72,   22,   93,   22,
       72,  108,   93,   22,   98,   98,  132,   72,   22,   99,

       99,  101,  101,  114,  146,  146,  108,  114,  148,  148,
      150,  150,  151,  151,  143,  132,  142,  141,  140,  139,
      132,  154,  154,  154,  154,  154,  154,  154,  155,  155,
      155,  155,  155,  155,  155,  156,  156,  156,  156,  156,
      156,  156,  157,  157,  157,  157,  157,  157,  157,  158,
      158,  158,  158,  158,  158,  158,  159,  159,  159,  159,
      159,  159,  159,  160,  160,  160,  160,  160,  160,  160,
      161,  161,  161,  161,  161,  161,  161,  162,  162,  162,
      162,  162,  162,  162,  163,  163,  163,  163,  163,  163,
      163,  164,  164,  164,  164,  164,  164,  164,  165,  138,

      137,  165,  166,  136,  135,  166,  166,  166,  166,  167,
      167,  134,  167,  133,  131,  167,  168,  168,  130,  168,
      168,  168,  168,  169,  129,  128,  169,  169,  169,  169,
      170,  127,  126,  170,  170,  170,  170,  171,  171,  125,
      171,  171,  171,  171,  172,  124,  123,  172,  172,  172,
      172,  173,  122,  121,  173,  173,  173,  173,  174,  120,
      119,  174,  174,  174,  174,  175,  175,  118,  175,  175,
      175,  175,  176,  176,  117,  176,  176,  176,  176,  177,
      177,  116,  177,  177,  115,  177,  178,  113,  112,  178,
      178,  178,  178,  179,  179,  179,  179,  179,  179,  179,

      181,  181,  109,  181,  181,  181,  181,  182,  182,  107,
      182,  182,  182,  182,  183,  183,  106,  183,  183,  183,
      183,  184,  184,  105,  184,  184,  184,  184,  185,  104,
       96,  185,  185,  185,  185,  186,  186,   92,  186,  186,
      186,  186,  187,  187,   91,  187,  187,  187,  187,   90,
       89,   88,   87,   86,   85,   83,   82,   81,   80,   79,
       78,   76,   74,   73,   71,   70,   69,   68,   67,   63,
       62,   61,   54,   50,   46,   44,   43,   42,   41,   38,
       37,   36,   35,   29,   27,   24,   23,   20,   19,   12,
       11,  153,  153,  153,  153,  153,  153,  153,  153,  153,

      153,  153,  153,  153,  153,  153,  153,  153,  153,  153,
      153,  153,  153,  153,  153,  153,  153,  153,  153,  153,
      153
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[49] =
    {   0,
0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 
    0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0,     };

extern int yy_flex_debug;
int yy_flex_debug = 1;

static const flex_int16_t yy_rule_linenum[48] =
    {   0,
      125,  126,  127,  128,  129,  130,  131,  132,  133,  134,
      135,  136,  138,  139,  140,  144,  145,  146,  147,  148,
      149,  150,  151,  152,  153,  157,  158,  159,  163,  164,
      165,  166,  167,  168,  169,  170,  171,  172,  173,  177,
      178,  179,  180,  181,  185,  186,  188
    } ;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
(yy_lp) = (yy_full_lp); /* restore orig. accepting pos. */ \
(yy_state_ptr) = (yy_full_state); /* restore orig. state */ \
yy_current_state = *(yy_state_ptr); /* restore curr. state */ \
++(yy_lp); \
goto find_rule; \
}

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "cbd.l"
#line 5 "cbd.l"

#define CBDLTYPE_IS_DECLARED 1

#include <ctype128.h>
#include <xsystem.h>
#include <iome.h>
#include "cbd.h"
#include "cbd.tab.h"
#include "pool.h"
#define YY_NO_UNISTD_H

#define yylloc cbdlloc
#define yylval cbdlval

/* keep-space-dup */
#define ksdup(s) yylval.text = (char*)pool_copy((unsigned char *)(s),curr_cbd->pool)

/* yytext-dup strips beginning/end spaces */
#define ytdup() (yylval.text = (char*)pool_copy((ucp)unspace(yytext),curr_cbd->pool))
#define ytdupn(n) yylval.text = (char*)pool_copy((ucp)unspace(yytext+(n)),curr_cbd->pool)
#define yi(tok) yylval.i = tok;
#define yln(s) if (ylntrace) {fprintf(stderr, "%s: %d\n",(s),yylineno);}

static int after_s_entsns = 0;
static int after_s_gw = 0;
static int after_s_pos = 0;
static int after_s_renmrg = 0;
extern char *efile;

static int base_state = BASE_PRI;
static int base_tok(void);

int bang, star;
extern List *cmt_queue;

static struct cbdtag *ctp;

#if 0
static int after_s_lang = 0;
static int yycolumn = 0;
static void baseco(const char *type);
static void basesc(const char *type);
static char *b_alt_tok = NULL;
static void alt_wrapup(int clean);
static void clean_alt_paren(void);
#endif

static int set_rws(void);
static int set_ctp(void);

static int tg_set_flags(char *f);

static char *unspace(char*s);
static void cbd_user_action(void);
#define mtch(x) fprintf(stderr,"matched %s",(x))

#define YY_USER_ACTION cbd_user_action();

int ylntrace = 0;
int mystate = 0;
#define ss(arg) (mystate=arg)

#define MAX_INCLUDE_DEPTH 10
struct bufstack
{
  char *file;
  int line;
  FILE *fp;
  YY_BUFFER_STATE yycb;
};
struct bufstack include_stack[MAX_INCLUDE_DEPTH];
int include_stack_ptr = 0;
/*static void includec(void);*/
static void includeo(char *file);

YY_BUFFER_STATE bp;

#if 1
#define xreturn(x) return(x)
#else
#define xreturn(x) return(tg_validate(x))
#endif

char *ssnames[] = {
"0",
"s_b",
"s_cf",
"s_f",
"s_flag",
"s_flush",
"s_gw",
"s_incl",
"s_pos",
"s_sol",
"s_s",
"s_lang",
"s_text",
"s_word"
};

#line 1101 "cbd-l.c"

#line 1103 "cbd-l.c"

#define INITIAL 0
#define s_b 1
#define s_cf 2
#define s_f 3
#define s_flag 4
#define s_flush 5
#define s_gw 6
#define s_incl 7
#define s_pos 8
#define s_sol 9
#define s_s 10
#define s_text 11
#define s_word 12

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
/* %if-c-only */
#include <unistd.h>
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* %if-c-only Reentrant structure and macros (non-C++). */
/* %if-reentrant */
/* %if-c-only */

static int yy_init_globals ( void );

/* %endif */
/* %if-reentrant */
/* %endif */
/* %endif End reentrant structures and macros. */

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* %if-bison-bridge */
/* %endif */

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

/* %not-for-header */
#ifndef YY_NO_UNPUT
    
#endif
/* %ok-for-header */

/* %endif */

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif
/* %ok-for-header */

/* %endif */
#endif

/* %if-c-only */

/* %endif */

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* %if-c-only Standard (non-C++) definition */
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
/* %% [5.0] fread()/read() definition of YY_INPUT goes here unless we're doing C++ \ */\
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\
/* %if-c++-only C++ definition \ */\
/* %endif */

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
/* %if-c-only */
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

/* %if-tables-serialization structures and prototypes */
/* %not-for-header */
/* %ok-for-header */

/* %not-for-header */
/* %tables-yydmap generated elements */
/* %endif */
/* end tables serialization structures and prototypes */

/* %ok-for-header */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
/* %if-c-only Standard (non-C++) definition */

extern int yylex (void);

#define YY_DECL int yylex (void)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

/* %% [6.0] YY_RULE_SETUP definition goes here */
#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/* %not-for-header */
/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
/* %if-c-only */
			yyin = stdin;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! yyout )
/* %if-c-only */
			yyout = stdout;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
/* %% [7.0] user's declarations go here */
#line 120 "cbd.l"


#line 123 "cbd.l"
	/* OUTER LEVEL TOKENIZER */

#line 1408 "cbd-l.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
/* %% [8.0] yymore()-related code goes here */
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

/* %% [9.0] code to set up and find next match goes here */
		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 154 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_current_state != 153 );

yy_find_action:
/* %% [10.0] code to find the action number goes here */
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     (yy_looking_for_trail_begin) )
					{
					if ( yy_act == (yy_looking_for_trail_begin) )
						{
						(yy_looking_for_trail_begin) = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					(yy_looking_for_trail_begin) = yy_act & ~YY_TRAILING_MASK;
					(yy_looking_for_trail_begin) |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					(yy_full_match) = yy_cp;
					(yy_full_state) = (yy_state_ptr);
					(yy_full_lp) = (yy_lp);
					break;
					}
				++(yy_lp);
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

/* %% [11.0] code for yylineno update goes here */

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

/* %% [12.0] debug code goes here */
		if ( yy_flex_debug )
			{
			if ( yy_act == 0 )
				fprintf( stderr, "--scanner backing up\n" );
			else if ( yy_act < 48 )
				fprintf( stderr, "--accepting rule at line %ld (\"%s\")\n",
				         (long)yy_rule_linenum[yy_act], yytext );
			else if ( yy_act == 48 )
				fprintf( stderr, "--accepting default rule (\"%s\")\n",
				         yytext );
			else if ( yy_act == 49 )
				fprintf( stderr, "--(end of buffer or a NUL)\n" );
			else
				fprintf( stderr, "--EOF (start condition %d)\n", YY_START );
			}

		switch ( yy_act )
	{ /* beginning of action switch */
/* %% [13.0] actions go here */
case 1:
YY_RULE_SETUP
#line 125 "cbd.l"
{ BEGIN ss(s_sol); 	 return(yytext[0]); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 126 "cbd.l"
{ after_s_gw=s_pos; after_s_pos=0; BEGIN ss(s_cf); return(RENAME); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 127 "cbd.l"
{ after_s_gw=s_pos; after_s_pos=0; BEGIN ss(s_cf); return(MERGE); }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 128 "cbd.l"
{ BEGIN ss(0); return(END_ENTRY); }
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 129 "cbd.l"
{ BEGIN ss(0); return(END_SENSES); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 130 "cbd.l"
{ if (set_ctp()) xreturn(ctp->tok); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 131 "cbd.l"
{ if (set_ctp()) BEGIN ss(s_flag); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 132 "cbd.l"
{ tg_set_flags(yytext) ; xreturn(ctp->tok); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 133 "cbd.l"
{ if (set_rws()) xreturn(DCF); } 
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 134 "cbd.l"
{ BEGIN ss(0); if (set_ctp()) xreturn(ctp->tok); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 135 "cbd.l"
{ /* empty */ }
	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 136 "cbd.l"
{ BEGIN ss(0); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 138 "cbd.l"
{ BEGIN ss(0); ksdup(yytext); xreturn(WORDSPEC); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 139 "cbd.l"
{ /* empty */ }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 140 "cbd.l"
{ BEGIN ss(0); ksdup(yytext); xreturn(TEXTSPEC); }
	YY_BREAK
/* CF-GW-POS TOKENIZER */
case 16:
YY_RULE_SETUP
#line 144 "cbd.l"
{ ytdup(); xreturn(CF); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 145 "cbd.l"
{ ytdup(); xreturn(CF); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 146 "cbd.l"
{ BEGIN ss(s_gw); xreturn(yytext[yyleng-1]); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 147 "cbd.l"
{ ytdup(); xreturn(GW); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 148 "cbd.l"
{ BEGIN ss(after_s_gw); xreturn(yytext[0]); }
	YY_BREAK
case 21:
/* rule 21 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 149 "cbd.l"
{ BEGIN ss(0); ytdup(); xreturn(POS); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 150 "cbd.l"
{ BEGIN ss(after_s_pos); ytdup(); xreturn(POS); }
	YY_BREAK
case 23:
/* rule 23 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 151 "cbd.l"
{ BEGIN ss(0); }
	YY_BREAK
case 24:
/* rule 24 can match eol */
YY_RULE_SETUP
#line 152 "cbd.l"
{ BEGIN ss(0); xreturn(EOL); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 153 "cbd.l"
{ /* empty */ }
	YY_BREAK
/* BASES TOKENIZER */
case 26:
YY_RULE_SETUP
#line 157 "cbd.l"
{ return base_tok(); }
	YY_BREAK
case 27:
/* rule 27 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 1);
(yy_c_buf_p) = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 158 "cbd.l"
{ BEGIN ss(0); base_state = BASE_PRI; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 159 "cbd.l"
{ /* empty */ }
	YY_BREAK
/* FORM TOKENIZER */
case 29:
YY_RULE_SETUP
#line 163 "cbd.l"
{ ytdupn(1); xreturn(FLANG); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 164 "cbd.l"
{ ytdupn(1); xreturn(FRWS); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 165 "cbd.l"
{ ytdupn(1); xreturn(FBASE); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 166 "cbd.l"
{ ytdupn(1); xreturn(FCONT); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 167 "cbd.l"
{ ytdupn(1); xreturn(FNORM); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 168 "cbd.l"
{ ytdupn(2); xreturn(FMORPH2); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 169 "cbd.l"
{ ytdupn(1); xreturn(FMORPH); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 170 "cbd.l"
{ ytdupn(1); xreturn(FSTEM); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 171 "cbd.l"
{ ytdup(); xreturn(FFORM); }
	YY_BREAK
case 38:
/* rule 38 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 1);
(yy_c_buf_p) = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 172 "cbd.l"
{ BEGIN ss(0); xreturn(END_FORM); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 173 "cbd.l"
{ /* empty */ }
	YY_BREAK
/* SENSE TOKENIZER */
case 40:
YY_RULE_SETUP
#line 177 "cbd.l"
{ ytdupn(1); return(yytext[0]); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 178 "cbd.l"
{ ytdupn(1); return(yytext[0]); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 179 "cbd.l"
{ ytdupn(1); return(yytext[0]); } /* error missing ']' */
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 180 "cbd.l"
{ BEGIN ss(s_text); ytdup(); return(POS); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 181 "cbd.l"
{ /* empty */ }
	YY_BREAK
/* INCLUDES TOKENIZER */
case 45:
YY_RULE_SETUP
#line 185 "cbd.l"
{ BEGIN ss(s_incl); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 186 "cbd.l"
{ includeo(yytext); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 188 "cbd.l"
{ BEGIN ss(0); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 190 "cbd.l"
ECHO;
	YY_BREAK
#line 1791 "cbd-l.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(s_b):
			case YY_STATE_EOF(s_cf):
			case YY_STATE_EOF(s_f):
			case YY_STATE_EOF(s_flag):
			case YY_STATE_EOF(s_flush):
			case YY_STATE_EOF(s_gw):
			case YY_STATE_EOF(s_incl):
			case YY_STATE_EOF(s_pos):
			case YY_STATE_EOF(s_sol):
			case YY_STATE_EOF(s_s):
			case YY_STATE_EOF(s_text):
			case YY_STATE_EOF(s_word):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
/* %if-c-only */
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
/* %endif */
/* %if-c++-only */
/* %endif */
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
/* %% [14.0] code to do back-up for compressed tables and set up yy_cp goes here */
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */
/* %ok-for-header */

/* %if-c++-only */
/* %not-for-header */
/* %ok-for-header */

/* %endif */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
/* %if-c-only */
static int yy_get_next_buffer (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

/* %if-c-only */
/* %not-for-header */
    static yy_state_type yy_get_previous_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
/* %% [15.0] code to get the start state into yy_current_state goes here */
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
/* %% [16.0] code to find the next state goes here */
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 154 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
/* %if-c-only */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	int yy_is_jam;
    /* %% [17.0] code to find the next state, and perhaps do backing up, goes here */

	YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 154 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 153);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT
/* %if-c-only */

/* %endif */
#endif

/* %if-c-only */
#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

/* %endif */
/* %if-c++-only */
/* %endif */
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

/* %% [19.0] update BOL and yylineno */
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		
    yylineno++;
;

	return c;
}
/* %if-c-only */
#endif	/* ifndef YY_NO_INPUT */
/* %endif */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
/* %if-c-only */
    void yyrestart  (FILE * input_file )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/* %if-c++-only */
/* %endif */

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
/* %if-c-only */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

/* %if-c-only */
static void yy_load_buffer_state  (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
/* %if-c-only */
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
/* %endif */
/* %if-c++-only */
/* %endif */
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
/* %if-c-only */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/* %if-c++-only */
/* %endif */

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
/* %if-c-only */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
/* %if-c-only */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )
/* %endif */
/* %if-c++-only */
/* %endif */

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

/* %if-c-only */
	b->yy_input_file = file;
/* %endif */
/* %if-c++-only */
/* %endif */
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

/* %if-c-only */

        b->yy_is_interactive = 0;
    
/* %endif */
/* %if-c++-only */
/* %endif */
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
/* %if-c-only */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/* %if-c-or-c++ */
/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
/* %if-c-only */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}
/* %endif */

/* %if-c-or-c++ */
/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
/* %if-c-only */
void yypop_buffer_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}
/* %endif */

/* %if-c-or-c++ */
/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
/* %if-c-only */
static void yyensure_buffer_stack (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}
/* %endif */

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

/* %if-c-only */
static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}
/* %endif */
/* %if-c++-only */
/* %endif */

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/* %if-c-only */
/* %if-reentrant */
/* %endif */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/* %if-reentrant */
/* %endif */

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

/* %endif */

/* %if-reentrant */
/* %if-bison-bridge */
/* %endif */
/* %endif if-c-only */

/* %if-c-only */
static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}
/* %endif */

/* %if-c-only SNIP! this currently causes conflicts with the c++ scanner */
/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

/* %if-reentrant */
/* %endif */
    return 0;
}
/* %endif */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

/* %if-tables-serialization definitions */
/* %define-yytables   The name for this specific scanner's tables. */
#define YYTABLES_NAME "yytables"
/* %endif */

/* %ok-for-header */

#line 190 "cbd.l"


void
set_after(void)
{
  switch (ctp->tok)
    {
      case ENTRY:
	after_s_renmrg = after_s_entsns = s_cf;
	after_s_gw = s_pos;
	after_s_pos = 0;
        break;
      case SENSE:
      case SENSEL:
	/*after_s_renmrg = after_s_entsns = after_s_gw = s_spos;*/
	break;
      case ALIAS:
	after_s_pos = 0;
        break;
      case PARTS:
	after_s_pos = s_cf;
        break;
      default:
        break;
    }
}

static int
set_rws(void)
{
  struct cbdrws *rws = NULL;
  const char *atname = yytext;
  while (*atname && '@' != *atname)
    ++atname;
  if (*atname)
    ++atname;
  rws = cbdrws(atname,strlen(atname));
  if (rws)
    {
      BEGIN ss(s_text);
      yylval.text = (char*)pool_copy((ucp)rws->lang, curr_cbd->pool);
      return 1;
    }
  else
    {
      BEGIN ss(s_flush); yylloc.file=efile; yylloc.line=yylineno;
      vyyerror(yylloc,"unknown RWS %s\n",atname, NULL);
      return 0;
    }
}

static int
set_ctp(void)
{
  const char *atname = yytext;
  while (*atname && '@' != *atname)
    ++atname;
  if (*atname)
    ++atname;
  ctp = cbdtags(atname,strlen(atname));
  if (!ctp)
    {
      BEGIN ss(s_flush); yylloc.file=efile; yylloc.line=yylineno;
      vyyerror(yylloc,"unknown at-command %s\n",atname, NULL);
      return 0;
    }
  else
    {
      if (!strcmp(atname, "end"))
	{
	  
	}
      BEGIN ss(ctp->ss); set_after();
    }
  return 1;
}

static int
tg_set_flags(char *f)
{
  while (*f)
    {
      if (*f == '*')
	star = 1;
      else if (*f == '!')
	bang = 1;
      else
	fprintf(stderr, "cbd: internal error: unhandled flag char %c\n", *f);
    }
  return ctp != NULL;
}

static int
base_tok(void)
{
  int ret_state = BASE_PRI;

  char *t = yytext;
  char *e = yytext + strlen(yytext);

  if ('(' == *t)
    {
      ++t;
      ret_state = BASE_ALT;
      if (';' == e[-1])
	{
	  if (')' == e[-2])
	    e[-2] = '\0';
	  else
	    e[-1] = '\0';
	  base_state = BASE_PRI;
	}
      else
	{
	  if (',' == e[-1])
	    e[-1] = '\0';	      
	  base_state = BASE_ALT;
	}
       }
  else if ('%' == *t)
    {
      ret_state = LANGSPEC;
      ++t;
    }
  else
    {
      ret_state = base_state;
    }
  ytdup();
  return ret_state;
}

#if 0
void
alt_wrapup(int clean)
{
  if (clean)
    clean_alt_paren(); 
  (void)pool_copy((ucp)unspace(b_alt_tok),curr_cbd->pool);
  free(b_alt_tok); 
  b_alt_tok = NULL;
}

static void
basesc(const char *type)
{
  yylloc.file=efile;
  yylloc.line=yylineno; 
  vyyerror(yylloc,"misplaced %s semi-colon\n", type, NULL);
}

static void
baseco(const char *type)
{
  yylloc.file=efile;
  yylloc.line=yylineno; 
  vyyerror(yylloc,"misplaced %s comma\n", type, NULL);
}

static void
clean_alt_paren(void)
{
  b_alt_tok[strlen(b_alt_tok)-1] = '\0';
}
#endif
       
static char *
unspace(char*s)
{
  int i = strlen(s);
  while (isspace(s[i-1]))
    --i;
  if (i >= 0)
    s[i] = '\0';
  return s;
}

static void
cbd_user_action(void)
{
  if (cbd_flex_debug)
    {
      if (cmt_queue)
	fprintf(stderr, "%s:%d: cmt_queue has %d items\n", efile, yylineno, (int)list_len(cmt_queue));
      fprintf(stderr, "%s:%d: cbd-flex: state=%s tok=::%s::\n", efile, yylineno, ssnames[mystate], yytext);
    }
  yylloc.file = efile;
  yylloc.line = yylineno;
}

#if 1
#define tg_validate(x) (x)
#else
static int
tg_validate(int retval)
{
  extern int input_validation;
  extern char *rnvcbd_yytext;

  if (input_validation && yytext && *yytext)
    {
      if (retval == DCF)
        { rnvcbd_yytext = yytext , rnvcbd_token(efile, yylineno, mystate, "@dcf"); }
      else
        rnvcbd_token(efile, yylineno, mystate, yytext);
    }
  return retval;
}
#endif

/* include_stack_ptr indexes into include_stack and gives the current
   state.  At the initial state, we push the top-level state into
   include_stack[0] and then the first include is include_stack[1].

   On closing an include, the state pointed to by include_stack_ptr is
   the one we are shutting down.
 */

static void
includeo(char *file)
{
  if ( include_stack_ptr >= MAX_INCLUDE_DEPTH )
    {
      fprintf( stderr, "Includes nested too deeply" );
      exit( 1 );
    }

  if (!include_stack_ptr)
    {
      /* ensure top-level state is saved first on stack */
      include_stack[include_stack_ptr].file = efile;
      include_stack[include_stack_ptr].line = yylineno;
      include_stack[include_stack_ptr].yycb = YY_CURRENT_BUFFER;
      include_stack[include_stack_ptr].fp = yyin;
    }

  ++include_stack_ptr;      

  efile = include_stack[include_stack_ptr].file = (char*)pool_copy((ucp)yytext,curr_cbd->pool);
  include_stack[include_stack_ptr].yycb = YY_CURRENT_BUFFER;
  include_stack[include_stack_ptr].line = yylineno;
  include_stack[include_stack_ptr].fp = yyin = xfopen( yytext, "r" );

  yylineno = 1;

  if (cbd_flex_debug) { fprintf(stderr, "%s:%d: include switching input to new file\n", efile, yylineno); }
  yy_switch_to_buffer(yy_create_buffer( yyin, YY_BUF_SIZE ) );
  BEGIN(ss(INITIAL));
}

#if 0
static void
includec(void)
{
  if (include_stack_ptr--)
    {
      fclose(include_stack[include_stack_ptr+1].fp);
      yy_delete_buffer( YY_CURRENT_BUFFER );
      yy_switch_to_buffer(include_stack[include_stack_ptr].yycb);
      efile = include_stack[include_stack_ptr].file;
      yylineno = include_stack[include_stack_ptr].line;
      yyin = include_stack[include_stack_ptr].fp;
      if (cbd_flex_debug)
        {
          fprintf(stderr, "%s:%d: include of %s complete\n", efile, yylineno,
        	  	           		             include_stack[include_stack_ptr+1].file);
        }
    }
}
#endif

void
cbd_l_init(Iome_io *ip)
{
  if (!ip->use_stdio)
    {
      errmsg_fn = ip->fn;
      efile = (char*)ip->fn;
      if ((ip->fp = xfopen(efile, "r")))
	yyrestart(ip->fp);
    }
}
void
cbd_l_term(void)
{
  
}


