#line 2 "cbd-l.c"

#line 4 "cbd-l.c"

#define YY_NO_INPUT 1
#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer cbd_create_buffer
#define yy_delete_buffer cbd_delete_buffer
#define yy_scan_buffer cbd_scan_buffer
#define yy_scan_string cbd_scan_string
#define yy_scan_bytes cbd_scan_bytes
#define yy_init_buffer cbd_init_buffer
#define yy_flush_buffer cbd_flush_buffer
#define yy_load_buffer_state cbd_load_buffer_state
#define yy_switch_to_buffer cbd_switch_to_buffer
#define yypush_buffer_state cbdpush_buffer_state
#define yypop_buffer_state cbdpop_buffer_state
#define yyensure_buffer_stack cbdensure_buffer_stack
#define yy_flex_debug cbd_flex_debug
#define yyin cbdin
#define yyleng cbdleng
#define yylex cbdlex
#define yylineno cbdlineno
#define yyout cbdout
#define yyrestart cbdrestart
#define yytext cbdtext
#define yywrap cbdwrap
#define yyalloc cbdalloc
#define yyrealloc cbdrealloc
#define yyfree cbdfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define cbd_create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer cbd_create_buffer
#endif

#ifdef yy_delete_buffer
#define cbd_delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer cbd_delete_buffer
#endif

#ifdef yy_scan_buffer
#define cbd_scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer cbd_scan_buffer
#endif

#ifdef yy_scan_string
#define cbd_scan_string_ALREADY_DEFINED
#else
#define yy_scan_string cbd_scan_string
#endif

#ifdef yy_scan_bytes
#define cbd_scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes cbd_scan_bytes
#endif

#ifdef yy_init_buffer
#define cbd_init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer cbd_init_buffer
#endif

#ifdef yy_flush_buffer
#define cbd_flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer cbd_flush_buffer
#endif

#ifdef yy_load_buffer_state
#define cbd_load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state cbd_load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define cbd_switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer cbd_switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define cbdpush_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state cbdpush_buffer_state
#endif

#ifdef yypop_buffer_state
#define cbdpop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state cbdpop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define cbdensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack cbdensure_buffer_stack
#endif

#ifdef yylex
#define cbdlex_ALREADY_DEFINED
#else
#define yylex cbdlex
#endif

#ifdef yyrestart
#define cbdrestart_ALREADY_DEFINED
#else
#define yyrestart cbdrestart
#endif

#ifdef yylex_init
#define cbdlex_init_ALREADY_DEFINED
#else
#define yylex_init cbdlex_init
#endif

#ifdef yylex_init_extra
#define cbdlex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra cbdlex_init_extra
#endif

#ifdef yylex_destroy
#define cbdlex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy cbdlex_destroy
#endif

#ifdef yyget_debug
#define cbdget_debug_ALREADY_DEFINED
#else
#define yyget_debug cbdget_debug
#endif

#ifdef yyset_debug
#define cbdset_debug_ALREADY_DEFINED
#else
#define yyset_debug cbdset_debug
#endif

#ifdef yyget_extra
#define cbdget_extra_ALREADY_DEFINED
#else
#define yyget_extra cbdget_extra
#endif

#ifdef yyset_extra
#define cbdset_extra_ALREADY_DEFINED
#else
#define yyset_extra cbdset_extra
#endif

#ifdef yyget_in
#define cbdget_in_ALREADY_DEFINED
#else
#define yyget_in cbdget_in
#endif

#ifdef yyset_in
#define cbdset_in_ALREADY_DEFINED
#else
#define yyset_in cbdset_in
#endif

#ifdef yyget_out
#define cbdget_out_ALREADY_DEFINED
#else
#define yyget_out cbdget_out
#endif

#ifdef yyset_out
#define cbdset_out_ALREADY_DEFINED
#else
#define yyset_out cbdset_out
#endif

#ifdef yyget_leng
#define cbdget_leng_ALREADY_DEFINED
#else
#define yyget_leng cbdget_leng
#endif

#ifdef yyget_text
#define cbdget_text_ALREADY_DEFINED
#else
#define yyget_text cbdget_text
#endif

#ifdef yyget_lineno
#define cbdget_lineno_ALREADY_DEFINED
#else
#define yyget_lineno cbdget_lineno
#endif

#ifdef yyset_lineno
#define cbdset_lineno_ALREADY_DEFINED
#else
#define yyset_lineno cbdset_lineno
#endif

#ifdef yywrap
#define cbdwrap_ALREADY_DEFINED
#else
#define yywrap cbdwrap
#endif

#ifdef yyalloc
#define cbdalloc_ALREADY_DEFINED
#else
#define yyalloc cbdalloc
#endif

#ifdef yyrealloc
#define cbdrealloc_ALREADY_DEFINED
#else
#define yyrealloc cbdrealloc
#endif

#ifdef yyfree
#define cbdfree_ALREADY_DEFINED
#else
#define yyfree cbdfree
#endif

#ifdef yytext
#define cbdtext_ALREADY_DEFINED
#else
#define yytext cbdtext
#endif

#ifdef yyleng
#define cbdleng_ALREADY_DEFINED
#else
#define yyleng cbdleng
#endif

#ifdef yyin
#define cbdin_ALREADY_DEFINED
#else
#define yyin cbdin
#endif

#ifdef yyout
#define cbdout_ALREADY_DEFINED
#else
#define yyout cbdout
#endif

#ifdef yy_flex_debug
#define cbd_flex_debug_ALREADY_DEFINED
#else
#define yy_flex_debug cbd_flex_debug
#endif

#ifdef yylineno
#define cbdlineno_ALREADY_DEFINED
#else
#define yylineno cbdlineno
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define cbdwrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 48
#define YY_END_OF_BUFFER 49
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_acclist[200] =
    {   0,
       47,   47,   49,    7,   48,    8,   48,    9,   48,    1,
        7,   48,    7,   48,   48,   48,    4,   48,   25,   48,
       48,   25,   48,   48,   31,   48,   48,   31,   48,   28,
       48,   33,   48,   11,   48,   12,   48,   14,   48,   13,
       48,   16,   48,   48,   17,   48,   44,   48,   48,   48,
       44,   48,   48,   48,   48,   44,   48,   46,   48,   47,
       48,    7,    8,    1,    7,    5,    7,    2,    7,16387,
        2,    7,16387,    2,    7,16387,    2,    7,16387,    6,
        4,   25,   25,   24,   25,   20,   25,   20,   24,   25,
       20,   23,   21,   22,   31,   31,   30,   31,   31,   29,

       28,   27,   33,   26,   32,   10,   13,   16,   16,   15,
       17,   44,   44,   42,   42,   40,   36,   44,   43,   39,
       38,   37,   44,   46,   47, 8195,    7,    2,    7,16387,
        2,    7,16387,    2,    7,16387,   24,   20,   25,   20,
       22,   30,   31,   32,   42,   41,   42,   40,   36,   44,
       43,   39,   38,   37,   44,    2,    7,16387,    2,    7,
    16387,    2,    7,16387,   41,   42,    2,    7,16387,    2,
        7,16387,    2,    7,16387,    2,    7,   19,16387,   34,
     8195,    7,    2,    7,16387,   19,    7,   18,   35,    2,
        7,16387,   18,   18,    2,    7,   45,16387,   45

    } ;

static const flex_int16_t yy_accept[156] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    2,    3,    4,    6,    8,
       10,   13,   15,   16,   17,   19,   21,   22,   24,   25,
       27,   28,   30,   32,   34,   36,   38,   40,   42,   44,
       45,   47,   49,   50,   51,   53,   54,   55,   56,   58,
       60,   62,   63,   64,   66,   68,   71,   74,   77,   80,
       81,   82,   83,   84,   86,   86,   86,   88,   91,   92,
       93,   94,   95,   96,   97,   97,   97,   99,  100,  101,
      102,  103,  104,  105,  106,  107,  107,  108,  109,  110,

      111,  111,  112,  113,  114,  115,  116,  117,  119,  120,
      121,  122,  124,  125,  126,  128,  131,  134,  137,  138,
      138,  140,  141,  142,  142,  144,  145,  146,  148,  149,
      151,  152,  153,  154,  156,  159,  162,  165,  167,  170,
      173,  176,  180,  181,  183,  186,  187,  189,  190,  193,
      194,  195,  199,  200,  200
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    1,    5,    6,    7,    1,    1,    8,
        1,    9,   10,   11,   12,    1,   13,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,   14,    1,
        1,   12,    1,   15,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       17,    1,   18,    1,    1,    1,   19,   20,   21,   22,

       23,   24,   25,   25,   26,   25,   25,   27,   28,   29,
       30,   25,   25,   31,   32,   25,   33,   25,   25,   25,
       25,   25,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[34] =
    {   0,
        1,    2,    3,    1,    1,    1,    1,    1,    1,    1,
        4,    1,    1,    5,    1,    1,    6,    7,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8
    } ;

static const flex_int16_t yy_base[186] =
    {   0,
        0,    2,  467,  466,    2,    4,    0,    0,   13,   16,
       29,   42,    7,   31,    4,   18,   26,   36,    0,    0,
       54,   67,   39,   44,  477,  476,  478,    0,  470,  483,
       42,   82,  483,    0,   62,   60,  114,  115,  116,  462,
      118,   24,   73,  119,  454,  483,  483,    0,   76,  122,
      483,  446,  442,    0,  438,    0,    0,    0,  430,    0,
        0,    0,  429,  124,  408,  133,  156,  108,   36,    0,
      122,  133,  137,  138,  141,  145,  142,  150,  421,  159,
      483,  414,  413,  406,  149,  164,  166,  167,  483,  168,
      483,  181,  483,  398,  397,  390,    0,  183,  185,  483,

      187,  483,  389,  382,  370,  366,  362,  361,  358,  352,
      350,  344,    0,    0,  187,  162,  173,  178,  483,  198,
      200,  343,  342,  203,  334,  328,  326,  318,  317,  234,
      233,  232,  231,  230,   62,  179,  184,  229,  190,  208,
      195,  211,  224,  214,  152,  215,  222,  219,  196,  191,
      152,  218,   56,  483,  237,  245,  253,  261,  269,  277,
      285,  293,  301,  309,  317,   43,  325,  333,  341,  349,
      357,  365,  373,  381,  389,  397,  405,  413,  421,  429,
      437,  445,  453,  461,  469
    } ;

static const flex_int16_t yy_def[186] =
    {   0,
      155,  155,  156,  156,  156,  156,  156,  156,  157,  157,
      158,  158,  159,  159,  160,  160,  161,  161,  156,  156,
      162,  162,  163,  163,  164,  164,  154,  165,  154,  154,
      165,  154,  154,  166,  154,  167,  154,  168,  154,  169,
      154,  170,  154,  154,  171,  154,  154,  172,  173,  154,
      154,  174,  175,  176,  177,  178,  179,  180,  181,  182,
      183,  165,  154,  165,  165,   32,   32,   67,   67,  166,
      154,  167,  154,  167,  154,  154,  168,  168,  184,  154,
      154,  154,  169,  154,  154,  154,  170,  154,  154,  154,
      154,  154,  154,  154,  171,  171,  172,  173,  154,  154,

      154,  154,  174,  154,  175,  185,  176,  177,  178,  179,
      180,  181,  182,  183,  165,   67,   67,   67,  154,  154,
      154,  154,  154,  154,  154,  154,  154,  185,  154,  154,
      154,  154,  154,  154,   67,   67,   67,  154,   67,   67,
       67,   67,  154,  165,   67,  154,  165,  154,   67,  154,
      154,   67,  154,    0,  154,  154,  154,  154,  154,  154,
      154,  154,  154,  154,  154,  154,  154,  154,  154,  154,
      154,  154,  154,  154,  154,  154,  154,  154,  154,  154,
      154,  154,  154,  154,  154
    } ;

static const flex_int16_t yy_nxt[517] =
    {   0,
      154,   29,   30,   29,   30,   35,   33,   35,   33,   33,
       35,   31,   35,   31,   37,   33,   32,   37,   33,   38,
       33,   47,   38,   46,   47,   88,   39,   50,   51,   39,
       41,   33,   33,   33,   89,   47,   42,   50,   51,   43,
       33,   33,   44,   41,   33,   33,   33,   46,   47,   42,
       70,   64,   43,   64,   66,   44,   33,  153,   53,   54,
       55,   73,   56,   57,  118,   71,   58,   74,   59,   33,
       71,   53,   54,   55,   90,   56,   57,   99,  100,   58,
       66,   59,   62,   91,  139,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   65,   62,   62,

       66,   67,   66,   66,   66,   68,   66,   69,   66,   66,
       66,   66,   66,   66,   66,   75,   73,   80,   81,   85,
       92,   93,   78,  101,  102,   71,   66,   76,   79,   82,
       71,   86,   94,   64,   73,   64,  115,  117,   73,   73,
       74,  115,   75,  121,  119,   74,  120,   81,   62,   78,
       85,  121,   66,  151,   76,   79,   66,   78,   66,  115,
       80,   81,   86,   79,  115,  124,   93,  125,   88,   90,
       66,   62,   82,  149,  116,   66,  154,   89,   91,   66,
       66,   66,   92,   93,   99,  100,   99,  100,  101,  102,
      115,   66,  151,  135,   94,  115,   66,   66,  137,  120,

       81,  121,   66,  136,  124,   93,  140,  119,   66,  143,
      141,  144,  146,   66,   66,  148,  146,  115,  152,  153,
      148,  142,  115,  151,  147,  143,   66,  145,  150,   66,
      138,  134,  133,  132,  131,  130,   66,   28,   28,   28,
       28,   28,   28,   28,   28,   33,   33,   33,   33,   33,
       33,   33,   33,   36,   36,   36,   36,   36,   36,   36,
       36,   40,   40,   40,   40,   40,   40,   40,   40,   45,
       45,   45,   45,   45,   45,   45,   45,   48,   48,   48,
       48,   48,   48,   48,   48,   49,   49,   49,   49,   49,
       49,   49,   49,   52,   52,   52,   52,   52,   52,   52,

       52,   60,   60,   60,   60,   60,   60,   60,   60,   61,
       61,   61,   61,   61,   61,   61,   61,   62,  129,  138,
       62,   62,   62,   62,   62,   72,   72,  127,   72,  126,
       72,   72,   72,   77,   77,  125,   77,   77,   77,   77,
       77,   83,   83,  123,  122,  134,   83,   83,   83,   87,
       87,  133,   87,  132,   87,   87,   87,   95,   95,  131,
       95,   95,  130,  129,   95,   97,   97,  127,   97,   97,
       97,  127,   97,   98,   98,   98,   98,   98,   98,   98,
       98,  103,  103,  104,  103,  103,  103,  103,  103,  105,
      104,   96,  105,  105,  105,  105,  105,  107,   96,  126,

      107,  107,  107,  107,  107,  108,  108,   84,  108,  108,
      108,  108,  108,  109,   84,  123,  109,  109,  109,  109,
      109,  110,  122,   65,  110,  110,  110,  110,  110,  111,
       63,  104,  111,  111,  111,  111,  111,  112,  112,  104,
      112,  112,  112,  112,  112,  113,  106,  104,  113,  113,
      113,  113,  113,  114,  114,   96,  114,  114,  114,  114,
      114,   79,   79,   84,   79,   79,   79,   79,   79,  128,
      128,   63,  128,  128,  128,  128,  128,  154,   33,   33,
       34,   34,   27,  154,  154,  154,  154,  154,  154,  154,
      154,  154,  154,  154,  154,  154,  154,  154,  154,  154,

      154,  154,  154,  154,  154,  154,  154,  154,  154,  154,
      154,  154,  154,  154,  154,  154
    } ;

static const flex_int16_t yy_chk[517] =
    {   0,
        0,    1,    1,    2,    2,    5,   15,    6,   13,   13,
        5,    2,    6,    2,    9,    9,    2,   10,   10,    9,
       16,   15,   10,   13,   13,   42,    9,   17,   17,   10,
       11,   11,   14,   14,   42,   16,   11,   18,   18,   11,
       23,   23,   11,   12,   12,   24,   24,   14,   14,   12,
      166,   31,   12,   31,   69,   12,   21,  153,   21,   21,
       21,   36,   21,   21,   69,   35,   21,   36,   21,   22,
       35,   22,   22,   22,   43,   22,   22,   49,   49,   22,
      135,   22,   32,   43,  135,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,

       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   37,   38,   39,   39,   41,
       44,   44,   38,   50,   50,   71,   68,   37,   38,   39,
       71,   41,   44,   64,   72,   64,   66,   68,   73,   74,
       72,   66,   75,   77,   73,   74,   76,   76,   66,   77,
       85,   78,   66,  151,   75,   77,   66,   78,   66,   67,
       80,   80,   85,   78,   67,   86,   86,   87,   88,   90,
      145,   67,   80,  145,   67,   67,   87,   88,   90,   67,
      116,   67,   92,   92,   98,   98,   99,   99,  101,  101,
      115,  117,  150,  116,   92,  115,  118,  136,  118,  120,

      120,  121,  137,  117,  124,  124,  136,  121,  139,  140,
      137,  140,  142,  141,  149,  144,  146,  144,  149,  152,
      148,  139,  144,  147,  142,  143,  140,  141,  146,  142,
      138,  134,  133,  132,  131,  130,  152,  155,  155,  155,
      155,  155,  155,  155,  155,  156,  156,  156,  156,  156,
      156,  156,  156,  157,  157,  157,  157,  157,  157,  157,
      157,  158,  158,  158,  158,  158,  158,  158,  158,  159,
      159,  159,  159,  159,  159,  159,  159,  160,  160,  160,
      160,  160,  160,  160,  160,  161,  161,  161,  161,  161,
      161,  161,  161,  162,  162,  162,  162,  162,  162,  162,

      162,  163,  163,  163,  163,  163,  163,  163,  163,  164,
      164,  164,  164,  164,  164,  164,  164,  165,  129,  128,
      165,  165,  165,  165,  165,  167,  167,  127,  167,  126,
      167,  167,  167,  168,  168,  125,  168,  168,  168,  168,
      168,  169,  169,  123,  122,  112,  169,  169,  169,  170,
      170,  111,  170,  110,  170,  170,  170,  171,  171,  109,
      171,  171,  108,  107,  171,  172,  172,  106,  172,  172,
      172,  105,  172,  173,  173,  173,  173,  173,  173,  173,
      173,  174,  174,  104,  174,  174,  174,  174,  174,  175,
      103,   96,  175,  175,  175,  175,  175,  176,   95,   94,

      176,  176,  176,  176,  176,  177,  177,   84,  177,  177,
      177,  177,  177,  178,   83,   82,  178,  178,  178,  178,
      178,  179,   79,   65,  179,  179,  179,  179,  179,  180,
       63,   59,  180,  180,  180,  180,  180,  181,  181,   55,
      181,  181,  181,  181,  181,  182,   53,   52,  182,  182,
      182,  182,  182,  183,  183,   45,  183,  183,  183,  183,
      183,  184,  184,   40,  184,  184,  184,  184,  184,  185,
      185,   29,  185,  185,  185,  185,  185,   27,   26,   25,
        4,    3,  154,  154,  154,  154,  154,  154,  154,  154,
      154,  154,  154,  154,  154,  154,  154,  154,  154,  154,

      154,  154,  154,  154,  154,  154,  154,  154,  154,  154,
      154,  154,  154,  154,  154,  154
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[49] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 
    0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0,     };

extern int yy_flex_debug;
int yy_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
(yy_lp) = (yy_full_lp); /* restore orig. accepting pos. */ \
(yy_state_ptr) = (yy_full_state); /* restore orig. state */ \
yy_current_state = *(yy_state_ptr); /* restore curr. state */ \
++(yy_lp); \
goto find_rule; \
}

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "cbd.l"
#line 5 "cbd.l"

#define CBDLTYPE_IS_DECLARED 1

#include <ctype128.h>
#include <xsystem.h>
#include <iome.h>
#include "cbd.h"
#include "cbd.tab.h"
/*#include "rnvcbd.h"*/
#include "pool.h"
#define YY_NO_UNISTD_H

#define yylloc cbdlloc
#define yylval cbdlval

/* keep-space-dup */
#define ksdup(s) yylval.text = (char*)pool_copy((unsigned char *)(s),curr_cbd->pool)

/* yytext-dup strips beginning/end spaces */
#define ytdup() (yylval.text = (char*)pool_copy((ucp)unspace(yytext),curr_cbd->pool))
#define ytdupn(n) yylval.text = (char*)pool_copy((ucp)unspace(yytext+(n)),curr_cbd->pool)
#define yi(tok) yylval.i = tok;
#define yln(s) if (ylntrace) {fprintf(stderr, "%s: %d\n",(s),yylineno);}

static int after_s_entsns = 0;
static int after_s_gw = 0;
static int after_s_pos = 0;
/*static int after_s_lang = 0;*/
static int after_s_renmrg = 0;
static int yycolumn = 0;
extern char *efile;

int bang, star;
extern List *cmt_queue;

static struct cbdtag *ctp;

static void baseco(const char *type);
static void basesc(const char *type);
static int set_ctp(void);

static int tg_set_flags(char *f);

#if 0
static int tg_validate(int retval);
#endif

static char *b_alt_tok = NULL;
static void alt_wrapup(int clean);
static void clean_alt_paren(void);
static char *unspace(char*s);
static void cbd_user_action(void);
#define mtch(x) fprintf(stderr,"matched %s",(x))

#define YY_USER_ACTION cbd_user_action();

int ylntrace = 0;
extern int flextrace;
int mystate = 0;
#define ss(arg) (mystate=arg)

char *ssnames[] = {
"0", "s_allow", "s_b", "s_bp", "s_b",
"s_cf", "s_gw", "s_pos", "s_spos",
"s_f", "s_s", "s_sw",
"s_proj", "s_lang", "s_text", "s_word", "s_entsns", "s_why",
"s_comment", "s_elang", "s_oid", "s_flush", "s_incl", 
};

#define MAX_INCLUDE_DEPTH 10
struct bufstack
{
  char *file;
  int line;
  FILE *fp;
  YY_BUFFER_STATE yycb;
};
struct bufstack include_stack[MAX_INCLUDE_DEPTH];
int include_stack_ptr = 0;
/*static void includec(void);*/
static void includeo(char *file);

YY_BUFFER_STATE bp;

#if 1
#define xreturn(x) return(x)
#else
#define xreturn(x) return(tg_validate(x))
#endif
#line 1028 "cbd-l.c"

#line 1030 "cbd-l.c"

#define INITIAL 0
#define s_sol 1
#define s_flag 2
#define s_b 3
#define s_bp 4
#define s_ba 5
#define s_cf 6
#define s_gw 7
#define s_pos 8
#define s_spos 9
#define s_f 10
#define s_incl 11
#define s_flush 12

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 101 "cbd.l"

#line 1270 "cbd-l.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 155 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_current_state != 154 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     (yy_looking_for_trail_begin) )
					{
					if ( yy_act == (yy_looking_for_trail_begin) )
						{
						(yy_looking_for_trail_begin) = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					(yy_looking_for_trail_begin) = yy_act & ~YY_TRAILING_MASK;
					(yy_looking_for_trail_begin) |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					(yy_full_match) = yy_cp;
					(yy_full_state) = (yy_state_ptr);
					(yy_full_lp) = (yy_lp);
					break;
					}
				++(yy_lp);
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 102 "cbd.l"
{ BEGIN ss(s_sol); 	 return(yytext[0]); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 103 "cbd.l"
{ if (set_ctp()) xreturn(ctp->tok); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 104 "cbd.l"
{ if (set_ctp()) BEGIN ss(s_flag); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 105 "cbd.l"
{ tg_set_flags(yytext) ; xreturn(ctp->tok); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 106 "cbd.l"
{ if (set_ctp()) xreturn(ctp->tok); } 
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 107 "cbd.l"
{ if (set_ctp()) xreturn(ctp->tok); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 108 "cbd.l"
{ ksdup(yytext); xreturn(TEXTSPEC); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 109 "cbd.l"
/* empty */
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 110 "cbd.l"
{ yycolumn=1; if (ctp->eol_sp) xreturn(TEXTSPEC); else xreturn(EOL); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 112 "cbd.l"
{ ytdup(); xreturn(CF); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 113 "cbd.l"
{ ytdup(); xreturn(CF); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 114 "cbd.l"
{ BEGIN ss(s_gw); xreturn(yytext[yyleng-1]); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 115 "cbd.l"
{ ytdup(); xreturn(GW); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 116 "cbd.l"
{ BEGIN ss(after_s_gw); xreturn(yytext[0]); }
	YY_BREAK
case 15:
/* rule 15 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 117 "cbd.l"
{ BEGIN ss(0); ytdup(); xreturn(POS); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 118 "cbd.l"
{ BEGIN ss(after_s_pos); ytdup(); xreturn(POS); }
	YY_BREAK
case 17:
/* rule 17 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 119 "cbd.l"
{ BEGIN ss(0); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 121 "cbd.l"
{ BEGIN ss(s_bp); basesc("initial"); xreturn(BASES); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 122 "cbd.l"
{ BEGIN ss(s_bp); xreturn(BASES); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 123 "cbd.l"
{ ytdupn(1); xreturn(LANGSPEC); }
	YY_BREAK
case 21:
/* rule 21 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 124 "cbd.l"
{ BEGIN ss(0); yycolumn = 1; basesc("final"); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 125 "cbd.l"
{ BEGIN ss(s_bp); basesc("double"); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 126 "cbd.l"
{ BEGIN ss(s_bp); }
	YY_BREAK
case 24:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 127 "cbd.l"
{ BEGIN ss(s_ba); ytdup(); xreturn(BASE_PRI); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 128 "cbd.l"
{ ytdup(); xreturn(BASE_PRI); }
	YY_BREAK
case 26:
/* rule 26 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 129 "cbd.l"
{ BEGIN ss(0); yycolumn = 1; basesc("final"); if (b_alt_tok) { alt_wrapup(1); xreturn(BASE_ALT); } }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 130 "cbd.l"
{ baseco("double"); unput(','); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 131 "cbd.l"
{ if (b_alt_tok) { alt_wrapup(0); xreturn(BASE_ALT); } }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 132 "cbd.l"
{ baseco("initial"); unput('('); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 133 "cbd.l"
{ b_alt_tok = strdup(yytext+1); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 134 "cbd.l"
{ b_alt_tok = strdup(yytext); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 135 "cbd.l"
{ BEGIN ss(s_bp); basesc("double"); if (b_alt_tok) { alt_wrapup(1); xreturn(BASE_ALT); } }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 136 "cbd.l"
{ BEGIN ss(s_bp); if (b_alt_tok) { alt_wrapup(1); xreturn(BASE_ALT); } }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 138 "cbd.l"
{ BEGIN ss(s_f); xreturn(FORM); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 139 "cbd.l"
{ BEGIN ss(s_f); bang = 1; xreturn(FORM); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 140 "cbd.l"
{ ytdupn(1); xreturn(FLANG); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 141 "cbd.l"
{ ytdupn(1); xreturn(FRWS); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 142 "cbd.l"
{ ytdupn(1); xreturn(FBASE); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 143 "cbd.l"
{ ytdupn(1); xreturn(FCONT); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 144 "cbd.l"
{ ytdupn(1); xreturn(FNORM); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 145 "cbd.l"
{ ytdupn(2); xreturn(FMORPH2); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 146 "cbd.l"
{ ytdupn(1); xreturn(FMORPH); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 147 "cbd.l"
{ ytdupn(1); xreturn(FSTEM); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 148 "cbd.l"
{ ytdup(); xreturn(FFORM); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 150 "cbd.l"
{ BEGIN ss(s_incl); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 151 "cbd.l"
{ includeo(yytext); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 153 "cbd.l"
{ BEGIN ss(0); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 155 "cbd.l"
ECHO;
	YY_BREAK
#line 1625 "cbd-l.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(s_sol):
			case YY_STATE_EOF(s_flag):
			case YY_STATE_EOF(s_b):
			case YY_STATE_EOF(s_bp):
			case YY_STATE_EOF(s_ba):
			case YY_STATE_EOF(s_cf):
			case YY_STATE_EOF(s_gw):
			case YY_STATE_EOF(s_pos):
			case YY_STATE_EOF(s_spos):
			case YY_STATE_EOF(s_f):
			case YY_STATE_EOF(s_incl):
			case YY_STATE_EOF(s_flush):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 155 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    
	YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 155 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 154);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 155 "cbd.l"


void
set_after(void)
{
  switch (ctp->tok)
    {
      case ENTRY:
        after_s_renmrg = after_s_entsns = s_cf; after_s_gw = s_pos; after_s_pos = 0;
        break;
      case SENSE:
      case SENSEL:
	after_s_renmrg = after_s_entsns = after_s_gw = s_spos;
	break;
      case ALIAS:
	after_s_pos = 0;
        break;
      case PARTS:
	after_s_pos = 0;
        break;
      default:
        break;
    }
}

static int
set_ctp(void)
{
  ctp = cbdtags(yytext,strlen(yytext));
  if (!ctp)
    {
      BEGIN ss(s_flush); yylloc.file=efile; yylloc.line=yylineno;
      vyyerror(yylloc,"unknown at-command %s\n",yytext, NULL);
      return 0;
    }
  else
    {
      BEGIN ss(ctp->ss); set_after();
    }
  return 1;
}

static int
tg_set_flags(char *f)
{
  while (*f)
    {
      if (*f == '*')
	star = 1;
      else if (*f == '!')
	bang = 1;
      else
	fprintf(stderr, "cbd: internal error: unhandled flag char %c\n", *f);
    }
  return ctp != NULL;
}

void
alt_wrapup(int clean)
{
  if (clean)
    clean_alt_paren(); 
  (void)pool_copy((ucp)unspace(b_alt_tok),curr_cbd->pool);
  free(b_alt_tok); 
  b_alt_tok = NULL;
}

static void
basesc(const char *type)
{
  yylloc.file=efile;
  yylloc.line=yylineno; 
  vyyerror(yylloc,"misplaced %s semi-colon\n", type, NULL);
}

static void
baseco(const char *type)
{
  yylloc.file=efile;
  yylloc.line=yylineno; 
  vyyerror(yylloc,"misplaced %s comma\n", type, NULL);
}

static void
clean_alt_paren(void)
{
  b_alt_tok[strlen(b_alt_tok)-1] = '\0';
}

static char *
unspace(char*s)
{
  int i = strlen(s);
  while (isspace(s[i-1]))
    --i;
  if (i >= 0)
    s[i] = '\0';
  return s;
}

static void
cbd_user_action(void)
{
  if (flextrace)
    {
      if (cmt_queue)
	fprintf(stderr, "%s:%d: cmt_queue has %d items\n", efile, yylineno, (int)list_len(cmt_queue));
      fprintf(stderr, "%s:%d: flextrace: state=%s tok=::%s::\n", efile, yylineno, ssnames[mystate], yytext);
    }
  yylloc.file = efile;
  yylloc.line = yylineno;
}

#if 1
#define tg_validate(x) (x)
#else
static int
tg_validate(int retval)
{
  extern int input_validation;
  extern char *rnvcbd_yytext;

  if (input_validation && yytext && *yytext)
    {
      if (retval == DCF)
        { rnvcbd_yytext = yytext , rnvcbd_token(efile, yylineno, mystate, "@dcf"); }
      else
        rnvcbd_token(efile, yylineno, mystate, yytext);
    }
  return retval;
}
#endif

/* include_stack_ptr indexes into include_stack and gives the current
   state.  At the initial state, we push the top-level state into
   include_stack[0] and then the first include is include_stack[1].

   On closing an include, the state pointed to by include_stack_ptr is
   the one we are shutting down.
 */

static void
includeo(char *file)
{
  if ( include_stack_ptr >= MAX_INCLUDE_DEPTH )
    {
      fprintf( stderr, "Includes nested too deeply" );
      exit( 1 );
    }

  if (!include_stack_ptr)
    {
      /* ensure top-level state is saved first on stack */
      include_stack[include_stack_ptr].file = efile;
      include_stack[include_stack_ptr].line = yylineno;
      include_stack[include_stack_ptr].yycb = YY_CURRENT_BUFFER;
      include_stack[include_stack_ptr].fp = yyin;
    }

  ++include_stack_ptr;      

  efile = include_stack[include_stack_ptr].file = (char*)pool_copy((ucp)yytext,curr_cbd->pool);
  include_stack[include_stack_ptr].yycb = YY_CURRENT_BUFFER;
  include_stack[include_stack_ptr].line = yylineno;
  include_stack[include_stack_ptr].fp = yyin = xfopen( yytext, "r" );

  yylineno = 1;

  if (flextrace) { fprintf(stderr, "%s:%d: include switching input to new file\n", efile, yylineno); }
  yy_switch_to_buffer(yy_create_buffer( yyin, YY_BUF_SIZE ) );
  BEGIN(ss(INITIAL));
}

#if 0
static void
includec(void)
{
  if (include_stack_ptr--)
    {
      fclose(include_stack[include_stack_ptr+1].fp);
      yy_delete_buffer( YY_CURRENT_BUFFER );
      yy_switch_to_buffer(include_stack[include_stack_ptr].yycb);
      efile = include_stack[include_stack_ptr].file;
      yylineno = include_stack[include_stack_ptr].line;
      yyin = include_stack[include_stack_ptr].fp;
      if (flextrace)
        {
          fprintf(stderr, "%s:%d: include of %s complete\n", efile, yylineno,
        	  	           		             include_stack[include_stack_ptr+1].file);
        }
    }
}
#endif

void
cbd_l_init(Iome_io *ip)
{
  if (!ip->use_stdio)
    {
      errmsg_fn = ip->fn;
      efile = (char*)ip->fn;
      if ((ip->fp = xfopen(efile, "r")))
	yyrestart(ip->fp);
    }
}
void
cbd_l_term(void)
{
  
}


