extern int edit_add(unsigned char **ll, struct entry *e);
extern int edit_check(struct cbd *c);
extern struct sense *parse_sense_sub(unsigned char *s, locator*lp);
extern int parse_dcf(struct entry *e, unsigned char *s);
extern unsigned char **parse_header(struct cbd *c, unsigned char **ll);
extern unsigned char **parse_entry(struct cbd *c, unsigned char **ll);
extern void parse_alias(struct entry *e, unsigned char *s, locator *lp);
extern void parse_allow(struct entry *e, unsigned char *s, locator *lp);
extern void parse_bases(struct entry *e, unsigned char *s, locator *lp);
extern void parse_bff(struct entry *e, unsigned char *s, locator *lp);
extern void parse_bib(struct entry *e, unsigned char *s, locator *lp);
extern void parse_disc(struct entry *e, unsigned char *s, locator *lp);
extern void parse_file(struct entry *e, unsigned char *s, locator *lp);
extern void parse_form(struct entry *e, unsigned char *s, locator *lp);
extern void parse_inote(struct entry *e, unsigned char *s, locator *lp);
extern void parse_isslp(struct entry *e, unsigned char *s, locator *lp);
extern void parse_note(struct entry *e, unsigned char *s, locator *lp);
extern void parse_parts(struct entry *e, unsigned char *s, locator *lp);
extern void parse_sense(struct entry *e, unsigned char *s, locator *lp);
extern void parse_collo(struct entry *e, unsigned char *s, locator *lp);
extern void parse_root(struct entry *e, unsigned char *s, locator *lp);
extern void parse_pl_id(struct entry *e, unsigned char *s, locator *lp);
extern void parse_pl_uid(struct entry *e, unsigned char *s, locator *lp);
extern void parse_pl_coord(struct entry *e, unsigned char *s, locator *lp);
extern void parse_prop(struct entry *e, unsigned char *s, locator *lp);
extern void parse_proplist(struct entry *e, unsigned char *s, locator *lp);
extern void parse_oid(struct entry *e, unsigned char *s, locator *lp);
extern void parse_phon(struct entry *e, unsigned char *s, locator *lp);
extern void parse_equiv(struct entry *e, unsigned char *s, locator *lp);
extern void parse_stems(struct entry *e, unsigned char *s, locator *lp);
extern void entry_edit(struct entry *e, char type);
extern struct sense *sense_edit(struct entry *e, char type);
extern void edit_save(struct entry *e, char ctxt, char type);
extern void edit_why(struct entry *e, char *why);
extern struct alias *alias_init(YYLTYPE l, struct entry *e);
extern void dcf_init(YYLTYPE l, struct entry *e, unsigned char *dcf, unsigned char *dcfarg);
extern struct parts *parts_init(YYLTYPE l, struct entry *e);
extern struct tag *tag_init(YYLTYPE l, struct entry *e, const char *name, unsigned char *val);
extern void proplist_add(struct cbd *c, char *text);
extern void allow_init(YYLTYPE l, struct entry *e, unsigned char *lhs, unsigned char *rhs);
extern void stem_init(YYLTYPE l, struct entry *e, unsigned char *stem);
extern struct sense *sense_init(YYLTYPE l, struct entry *e);
extern void bases_pri_save(YYLTYPE l, struct entry *e, unsigned char *lang, unsigned char *p);
extern void bases_alt_save(YYLTYPE l, struct entry *e, unsigned char *p);
extern struct f2 *form_init(YYLTYPE l, struct entry *e);
extern struct meta *meta_init(struct entry *e);
extern void meta_add(YYLTYPE l, struct entry *e, struct meta *mp, int tok, const char *name, void *val);
extern struct equiv *equiv_init(struct entry *e, unsigned char *lang, unsigned char *text);
extern struct pleiades *pleiades_init(struct entry *e,
				      unsigned char *coord, unsigned char *id, unsigned char *uid);
struct cbd * cbd_init(void);
void cbd_setup(struct cbd*c);
struct entry * entry_init(YYLTYPE l, struct cbd* c);
