/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class estraier_Database */

#ifndef _Included_estraier_Database
#define _Included_estraier_Database
#ifdef __cplusplus
extern "C" {
#endif
#undef estraier_Database_ERRNOERR
#define estraier_Database_ERRNOERR 0L
#undef estraier_Database_ERRINVAL
#define estraier_Database_ERRINVAL 1L
#undef estraier_Database_ERRACCES
#define estraier_Database_ERRACCES 2L
#undef estraier_Database_ERRLOCK
#define estraier_Database_ERRLOCK 3L
#undef estraier_Database_ERRDB
#define estraier_Database_ERRDB 4L
#undef estraier_Database_ERRIO
#define estraier_Database_ERRIO 5L
#undef estraier_Database_ERRNOITEM
#define estraier_Database_ERRNOITEM 6L
#undef estraier_Database_ERRMISC
#define estraier_Database_ERRMISC 9999L
#undef estraier_Database_DBREADER
#define estraier_Database_DBREADER 1L
#undef estraier_Database_DBWRITER
#define estraier_Database_DBWRITER 2L
#undef estraier_Database_DBCREAT
#define estraier_Database_DBCREAT 4L
#undef estraier_Database_DBTRUNC
#define estraier_Database_DBTRUNC 8L
#undef estraier_Database_DBNOLCK
#define estraier_Database_DBNOLCK 16L
#undef estraier_Database_DBLCKNB
#define estraier_Database_DBLCKNB 32L
#undef estraier_Database_DBPERFNG
#define estraier_Database_DBPERFNG 1024L
#undef estraier_Database_DBCHRCAT
#define estraier_Database_DBCHRCAT 2048L
#undef estraier_Database_DBSMALL
#define estraier_Database_DBSMALL 1048576L
#undef estraier_Database_DBLARGE
#define estraier_Database_DBLARGE 2097152L
#undef estraier_Database_DBHUGE
#define estraier_Database_DBHUGE 4194304L
#undef estraier_Database_DBHUGE2
#define estraier_Database_DBHUGE2 8388608L
#undef estraier_Database_DBHUGE3
#define estraier_Database_DBHUGE3 16777216L
#undef estraier_Database_DBSCVOID
#define estraier_Database_DBSCVOID 33554432L
#undef estraier_Database_DBSCINT
#define estraier_Database_DBSCINT 67108864L
#undef estraier_Database_DBSCASIS
#define estraier_Database_DBSCASIS 134217728L
#undef estraier_Database_IDXATTRSEQ
#define estraier_Database_IDXATTRSEQ 0L
#undef estraier_Database_IDXATTRSTR
#define estraier_Database_IDXATTRSTR 1L
#undef estraier_Database_IDXATTRNUM
#define estraier_Database_IDXATTRNUM 2L
#undef estraier_Database_OPTNOPURGE
#define estraier_Database_OPTNOPURGE 1L
#undef estraier_Database_OPTNODBOPT
#define estraier_Database_OPTNODBOPT 2L
#undef estraier_Database_MGCLEAN
#define estraier_Database_MGCLEAN 1L
#undef estraier_Database_PDCLEAN
#define estraier_Database_PDCLEAN 1L
#undef estraier_Database_PDWEIGHT
#define estraier_Database_PDWEIGHT 2L
#undef estraier_Database_ODCLEAN
#define estraier_Database_ODCLEAN 1L
#undef estraier_Database_GDNOATTR
#define estraier_Database_GDNOATTR 1L
#undef estraier_Database_GDNOTEXT
#define estraier_Database_GDNOTEXT 2L
#undef estraier_Database_GDNOKWD
#define estraier_Database_GDNOKWD 4L
/*
 * Class:     estraier_Database
 * Method:    search_meta
 * Signature: ([Lestraier/Database;Lestraier/Condition;)Lestraier/Result;
 */
JNIEXPORT jobject JNICALL Java_estraier_Database_search_1meta
  (JNIEnv *, jclass, jobjectArray, jobject);

/*
 * Class:     estraier_Database
 * Method:    version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_estraier_Database_version
  (JNIEnv *, jclass);

/*
 * Class:     estraier_Database
 * Method:    err_msg
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_estraier_Database_err_1msg
  (JNIEnv *, jobject, jint);

/*
 * Class:     estraier_Database
 * Method:    open
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_estraier_Database_open
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     estraier_Database
 * Method:    close
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_estraier_Database_close
  (JNIEnv *, jobject);

/*
 * Class:     estraier_Database
 * Method:    error
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_estraier_Database_error
  (JNIEnv *, jobject);

/*
 * Class:     estraier_Database
 * Method:    fatal
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_estraier_Database_fatal
  (JNIEnv *, jobject);

/*
 * Class:     estraier_Database
 * Method:    add_attr_index
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_estraier_Database_add_1attr_1index
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     estraier_Database
 * Method:    flush
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_estraier_Database_flush
  (JNIEnv *, jobject, jint);

/*
 * Class:     estraier_Database
 * Method:    sync
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_estraier_Database_sync
  (JNIEnv *, jobject);

/*
 * Class:     estraier_Database
 * Method:    optimize
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_estraier_Database_optimize
  (JNIEnv *, jobject, jint);

/*
 * Class:     estraier_Database
 * Method:    merge
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_estraier_Database_merge
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     estraier_Database
 * Method:    put_doc
 * Signature: (Lestraier/Document;I)Z
 */
JNIEXPORT jboolean JNICALL Java_estraier_Database_put_1doc
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     estraier_Database
 * Method:    out_doc
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_estraier_Database_out_1doc
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     estraier_Database
 * Method:    edit_doc
 * Signature: (Lestraier/Document;)Z
 */
JNIEXPORT jboolean JNICALL Java_estraier_Database_edit_1doc
  (JNIEnv *, jobject, jobject);

/*
 * Class:     estraier_Database
 * Method:    get_doc
 * Signature: (II)Lestraier/Document;
 */
JNIEXPORT jobject JNICALL Java_estraier_Database_get_1doc
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     estraier_Database
 * Method:    get_doc_attr
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_estraier_Database_get_1doc_1attr
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     estraier_Database
 * Method:    uri_to_id
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_estraier_Database_uri_1to_1id
  (JNIEnv *, jobject, jstring);

/*
 * Class:     estraier_Database
 * Method:    name
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_estraier_Database_name
  (JNIEnv *, jobject);

/*
 * Class:     estraier_Database
 * Method:    doc_num
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_estraier_Database_doc_1num
  (JNIEnv *, jobject);

/*
 * Class:     estraier_Database
 * Method:    word_num
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_estraier_Database_word_1num
  (JNIEnv *, jobject);

/*
 * Class:     estraier_Database
 * Method:    size
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_estraier_Database_size
  (JNIEnv *, jobject);

/*
 * Class:     estraier_Database
 * Method:    search
 * Signature: (Lestraier/Condition;)Lestraier/Result;
 */
JNIEXPORT jobject JNICALL Java_estraier_Database_search
  (JNIEnv *, jobject, jobject);

/*
 * Class:     estraier_Database
 * Method:    scan_doc
 * Signature: (Lestraier/Document;Lestraier/Condition;)Z
 */
JNIEXPORT jboolean JNICALL Java_estraier_Database_scan_1doc
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     estraier_Database
 * Method:    set_cache_size
 * Signature: (DIII)V
 */
JNIEXPORT void JNICALL Java_estraier_Database_set_1cache_1size
  (JNIEnv *, jobject, jdouble, jint, jint, jint);

/*
 * Class:     estraier_Database
 * Method:    add_pseudo_index
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_estraier_Database_add_1pseudo_1index
  (JNIEnv *, jobject, jstring);

/*
 * Class:     estraier_Database
 * Method:    set_wildmax
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_estraier_Database_set_1wildmax
  (JNIEnv *, jobject, jint);

/*
 * Class:     estraier_Database
 * Method:    set_informer
 * Signature: (Lestraier/DatabaseInformer;)V
 */
JNIEXPORT void JNICALL Java_estraier_Database_set_1informer
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
