/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class estraier_Document */

#ifndef _Included_estraier_Document
#define _Included_estraier_Document
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     estraier_Document
 * Method:    add_attr
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_estraier_Document_add_1attr
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     estraier_Document
 * Method:    add_text
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_estraier_Document_add_1text
  (JNIEnv *, jobject, jstring);

/*
 * Class:     estraier_Document
 * Method:    add_hidden_text
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_estraier_Document_add_1hidden_1text
  (JNIEnv *, jobject, jstring);

/*
 * Class:     estraier_Document
 * Method:    set_keywords
 * Signature: (Ljava/util/Map;)V
 */
JNIEXPORT void JNICALL Java_estraier_Document_set_1keywords
  (JNIEnv *, jobject, jobject);

/*
 * Class:     estraier_Document
 * Method:    set_score
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_estraier_Document_set_1score
  (JNIEnv *, jobject, jint);

/*
 * Class:     estraier_Document
 * Method:    id
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_estraier_Document_id
  (JNIEnv *, jobject);

/*
 * Class:     estraier_Document
 * Method:    attr_names
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_estraier_Document_attr_1names
  (JNIEnv *, jobject);

/*
 * Class:     estraier_Document
 * Method:    attr
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_estraier_Document_attr
  (JNIEnv *, jobject, jstring);

/*
 * Class:     estraier_Document
 * Method:    texts
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_estraier_Document_texts
  (JNIEnv *, jobject);

/*
 * Class:     estraier_Document
 * Method:    cat_texts
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_estraier_Document_cat_1texts
  (JNIEnv *, jobject);

/*
 * Class:     estraier_Document
 * Method:    keywords
 * Signature: ()Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_estraier_Document_keywords
  (JNIEnv *, jobject);

/*
 * Class:     estraier_Document
 * Method:    score
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_estraier_Document_score
  (JNIEnv *, jobject);

/*
 * Class:     estraier_Document
 * Method:    dump_draft
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_estraier_Document_dump_1draft
  (JNIEnv *, jobject);

/*
 * Class:     estraier_Document
 * Method:    make_snippet
 * Signature: (Ljava/util/List;III)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_estraier_Document_make_1snippet
  (JNIEnv *, jobject, jobject, jint, jint, jint);

/*
 * Class:     estraier_Document
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_estraier_Document_initialize__
  (JNIEnv *, jobject);

/*
 * Class:     estraier_Document
 * Method:    initialize
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_estraier_Document_initialize__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     estraier_Document
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_estraier_Document_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
