/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class estraier_Condition */

#ifndef _Included_estraier_Condition
#define _Included_estraier_Condition
#ifdef __cplusplus
extern "C" {
#endif
#undef estraier_Condition_SURE
#define estraier_Condition_SURE 1L
#undef estraier_Condition_USUAL
#define estraier_Condition_USUAL 2L
#undef estraier_Condition_FAST
#define estraier_Condition_FAST 4L
#undef estraier_Condition_AGITO
#define estraier_Condition_AGITO 8L
#undef estraier_Condition_NOIDF
#define estraier_Condition_NOIDF 16L
#undef estraier_Condition_SIMPLE
#define estraier_Condition_SIMPLE 1024L
#undef estraier_Condition_ROUGH
#define estraier_Condition_ROUGH 2048L
#undef estraier_Condition_UNION
#define estraier_Condition_UNION 32768L
#undef estraier_Condition_ISECT
#define estraier_Condition_ISECT 65536L
#undef estraier_Condition_ECLSIMURL
#define estraier_Condition_ECLSIMURL 10.0
#undef estraier_Condition_ECLSERV
#define estraier_Condition_ECLSERV 100.0
#undef estraier_Condition_ECLDIR
#define estraier_Condition_ECLDIR 101.0
#undef estraier_Condition_ECLFILE
#define estraier_Condition_ECLFILE 102.0
/*
 * Class:     estraier_Condition
 * Method:    set_phrase
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_estraier_Condition_set_1phrase
  (JNIEnv *, jobject, jstring);

/*
 * Class:     estraier_Condition
 * Method:    add_attr
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_estraier_Condition_add_1attr
  (JNIEnv *, jobject, jstring);

/*
 * Class:     estraier_Condition
 * Method:    set_order
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_estraier_Condition_set_1order
  (JNIEnv *, jobject, jstring);

/*
 * Class:     estraier_Condition
 * Method:    set_max
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_estraier_Condition_set_1max
  (JNIEnv *, jobject, jint);

/*
 * Class:     estraier_Condition
 * Method:    set_skip
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_estraier_Condition_set_1skip
  (JNIEnv *, jobject, jint);

/*
 * Class:     estraier_Condition
 * Method:    set_options
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_estraier_Condition_set_1options
  (JNIEnv *, jobject, jint);

/*
 * Class:     estraier_Condition
 * Method:    set_auxiliary
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_estraier_Condition_set_1auxiliary
  (JNIEnv *, jobject, jint);

/*
 * Class:     estraier_Condition
 * Method:    set_eclipse
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_estraier_Condition_set_1eclipse
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     estraier_Condition
 * Method:    set_distinct
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_estraier_Condition_set_1distinct
  (JNIEnv *, jobject, jstring);

/*
 * Class:     estraier_Condition
 * Method:    set_mask
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_estraier_Condition_set_1mask
  (JNIEnv *, jobject, jint);

/*
 * Class:     estraier_Condition
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_estraier_Condition_initialize
  (JNIEnv *, jobject);

/*
 * Class:     estraier_Condition
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_estraier_Condition_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
