#! /bin/sh

#================================================================
# stepcount
# Find files including dispensable tab characters
#================================================================


# set variables
PATH="$PATH:/usr/local/bin:.:.." ; export PATH
LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib:.:..:../.." ; export LD_LIBRARY_PATH
regex='(\.h|\.c|\.cc|\.java|\.pl|\.pm|\.xs|\.rb|\.js)$'


# count steps
files=`find . -type f | egrep $regex`
wc -l $files | sort -n


# exit normally
exit 0



# END OF FILE
