#ifndef NULL
#define NULL (char *)0
#endif
#include "xnn.h"
#include "ns-asl.h"
struct xnn_nstab asl_nstab[] = {
  { asl_n_g, "xmlns:g", "http://oracc.org/ns/gdl/1.0" },
  { asl_n_n, "xmlns:n", "http://oracc.org/ns/norm/1.0" },
  { asl_n_sl, "xmlns:sl", "http://oracc.org/ns/sl/1.0" },
  { asl_a_enum_top, NULL, NULL },
};

struct xnn_xname asl_anames[] =
{
  { "xmlns:g", "xmlns:g" },
  { "xmlns:n", "xmlns:n" },
  { "xmlns:sl", "xmlns:sl" },
  { "xmlns:xml", "xmlns:xml" },
  { "base", "base" },
  { "bau", "bau" },
  { "comment", "comment" },
  { "deprecated", "deprecated" },
  { "elles", "elles" },
  { "form", "form" },
  { "g:accented", "http://oracc.org/ns/gdl/1.0:accented" },
  { "g:delim", "http://oracc.org/ns/gdl/1.0:delim" },
  { "g:logolang", "http://oracc.org/ns/gdl/1.0:logolang" },
  { "g:pos", "http://oracc.org/ns/gdl/1.0:pos" },
  { "g:role", "http://oracc.org/ns/gdl/1.0:role" },
  { "g:status", "http://oracc.org/ns/gdl/1.0:status" },
  { "g:type", "http://oracc.org/ns/gdl/1.0:type" },
  { "g:utf8", "http://oracc.org/ns/gdl/1.0:utf8" },
  { "hex", "hex" },
  { "hzl", "hzl" },
  { "kwu", "kwu" },
  { "lak", "lak" },
  { "mzl", "mzl" },
  { "n", "n" },
  { "name", "name" },
  { "o", "o" },
  { "obzl", "obzl" },
  { "ogsl", "ogsl" },
  { "p", "p" },
  { "project", "project" },
  { "qm", "qm" },
  { "qn", "qn" },
  { "rec", "rec" },
  { "ref", "ref" },
  { "rsp", "rsp" },
  { "sexified", "sexified" },
  { "sllha", "sllha" },
  { "title", "title" },
  { "type", "type" },
  { "uncertain", "uncertain" },
  { "var", "var" },
  { "varid", "varid" },
  { "xml:id", "http://www.w3.org/XML/1998/namespace:id" },
  { "xml:lang", "http://www.w3.org/XML/1998/namespace:lang" },
  { "zatu", "zatu" },
  { NULL, NULL },
};
struct xnn_attr asl_abases[] =
{
  { { "base",NULL } , { "base",NULL } },
  { { "bau",NULL } , { "bau",NULL } },
  { { "comment",NULL } , { "comment",NULL } },
  { { "deprecated",NULL } , { "deprecated",NULL } },
  { { "elles",NULL } , { "elles",NULL } },
  { { "form",NULL } , { "form",NULL } },
  { { "g:accented",NULL } , { "http://oracc.org/ns/gdl/1.0:accented",NULL } },
  { { "g:delim",NULL } , { "http://oracc.org/ns/gdl/1.0:delim",NULL } },
  { { "g:logolang",NULL } , { "http://oracc.org/ns/gdl/1.0:logolang",NULL } },
  { { "g:pos",NULL } , { "http://oracc.org/ns/gdl/1.0:pos",NULL } },
  { { "g:role",NULL } , { "http://oracc.org/ns/gdl/1.0:role",NULL } },
  { { "g:status",NULL } , { "http://oracc.org/ns/gdl/1.0:status",NULL } },
  { { "g:type",NULL } , { "http://oracc.org/ns/gdl/1.0:type",NULL } },
  { { "g:utf8",NULL } , { "http://oracc.org/ns/gdl/1.0:utf8",NULL } },
  { { "hex",NULL } , { "hex",NULL } },
  { { "hzl",NULL } , { "hzl",NULL } },
  { { "kwu",NULL } , { "kwu",NULL } },
  { { "lak",NULL } , { "lak",NULL } },
  { { "mzl",NULL } , { "mzl",NULL } },
  { { "n",NULL } , { "n",NULL } },
  { { "name",NULL } , { "name",NULL } },
  { { "o",NULL } , { "o",NULL } },
  { { "obzl",NULL } , { "obzl",NULL } },
  { { "ogsl",NULL } , { "ogsl",NULL } },
  { { "p",NULL } , { "p",NULL } },
  { { "project",NULL } , { "project",NULL } },
  { { "qm",NULL } , { "qm",NULL } },
  { { "qn",NULL } , { "qn",NULL } },
  { { "rec",NULL } , { "rec",NULL } },
  { { "ref",NULL } , { "ref",NULL } },
  { { "rsp",NULL } , { "rsp",NULL } },
  { { "sexified",NULL } , { "sexified",NULL } },
  { { "sllha",NULL } , { "sllha",NULL } },
  { { "title",NULL } , { "title",NULL } },
  { { "type",NULL } , { "type",NULL } },
  { { "uncertain",NULL } , { "uncertain",NULL } },
  { { "var",NULL } , { "var",NULL } },
  { { "varid",NULL } , { "varid",NULL } },
  { { "xml:id",NULL } , { "http://www.w3.org/XML/1998/namespace:id",NULL } },
  { { "xml:lang",NULL } , { "http://www.w3.org/XML/1998/namespace:lang",NULL } },
  { { "zatu",NULL } , { "zatu",NULL } },
  { { NULL,NULL } , { NULL,NULL } },
};
struct xnn_xname asl_enames[] =
{
  { "g:a", "http://oracc.org/ns/gdl/1.0:a" },
  { "g:b", "http://oracc.org/ns/gdl/1.0:b" },
  { "g:c", "http://oracc.org/ns/gdl/1.0:c" },
  { "g:d", "http://oracc.org/ns/gdl/1.0:d" },
  { "g:g", "http://oracc.org/ns/gdl/1.0:g" },
  { "g:gg", "http://oracc.org/ns/gdl/1.0:gg" },
  { "g:m", "http://oracc.org/ns/gdl/1.0:m" },
  { "g:n", "http://oracc.org/ns/gdl/1.0:n" },
  { "g:nonw", "http://oracc.org/ns/gdl/1.0:nonw" },
  { "g:o", "http://oracc.org/ns/gdl/1.0:o" },
  { "g:p", "http://oracc.org/ns/gdl/1.0:p" },
  { "g:q", "http://oracc.org/ns/gdl/1.0:q" },
  { "g:r", "http://oracc.org/ns/gdl/1.0:r" },
  { "g:s", "http://oracc.org/ns/gdl/1.0:s" },
  { "g:v", "http://oracc.org/ns/gdl/1.0:v" },
  { "g:w", "http://oracc.org/ns/gdl/1.0:w" },
  { "n:s", "http://oracc.org/ns/norm/1.0:s" },
  { "n:w", "http://oracc.org/ns/norm/1.0:w" },
  { "sl:form", "http://oracc.org/ns/sl/1.0:form" },
  { "sl:inherited", "http://oracc.org/ns/sl/1.0:inherited" },
  { "sl:inote", "http://oracc.org/ns/sl/1.0:inote" },
  { "sl:iv", "http://oracc.org/ns/sl/1.0:iv" },
  { "sl:letter", "http://oracc.org/ns/sl/1.0:letter" },
  { "sl:list", "http://oracc.org/ns/sl/1.0:list" },
  { "sl:name", "http://oracc.org/ns/sl/1.0:name" },
  { "sl:note", "http://oracc.org/ns/sl/1.0:note" },
  { "sl:pname", "http://oracc.org/ns/sl/1.0:pname" },
  { "sl:proof", "http://oracc.org/ns/sl/1.0:proof" },
  { "sl:q", "http://oracc.org/ns/sl/1.0:q" },
  { "sl:qs", "http://oracc.org/ns/sl/1.0:qs" },
  { "sl:sign", "http://oracc.org/ns/sl/1.0:sign" },
  { "sl:signlist", "http://oracc.org/ns/sl/1.0:signlist" },
  { "sl:signs", "http://oracc.org/ns/sl/1.0:signs" },
  { "sl:sort", "http://oracc.org/ns/sl/1.0:sort" },
  { "sl:uname", "http://oracc.org/ns/sl/1.0:uname" },
  { "sl:unote", "http://oracc.org/ns/sl/1.0:unote" },
  { "sl:uphase", "http://oracc.org/ns/sl/1.0:uphase" },
  { "sl:utf8", "http://oracc.org/ns/sl/1.0:utf8" },
  { "sl:v", "http://oracc.org/ns/sl/1.0:v" },
  { NULL, NULL },
};
struct xnn_data asl_data = { asl_enames, asl_anames, asl_nstab };
