#ifndef NULL
#define NULL (char *)0
#endif
#include "xnn.h"
#include "ns-asl.h"
struct xnn_nstab asl_nstab[] = {
  { asl_n_sl, "xmlns:sl", "http://oracc.org/ns/sl/1.0" },
  { asl_a_enum_top, NULL, NULL },
};

struct xnn_xname asl_anames[] =
{
  { "xmlns:sl", "xmlns:sl" },
  { "xmlns:xml", "xmlns:xml" },
  { "base", "base" },
  { "bau", "bau" },
  { "comment", "comment" },
  { "deprecated", "deprecated" },
  { "elles", "elles" },
  { "hex", "hex" },
  { "hzl", "hzl" },
  { "id", "id" },
  { "kw", "kw" },
  { "kwu", "kwu" },
  { "lak", "lak" },
  { "lang", "lang" },
  { "mzl", "mzl" },
  { "n", "n" },
  { "name", "name" },
  { "o", "o" },
  { "obzl", "obzl" },
  { "ogsl", "ogsl" },
  { "p", "p" },
  { "project", "project" },
  { "qm", "qm" },
  { "qn", "qn" },
  { "rec", "rec" },
  { "ref", "ref" },
  { "rsp", "rsp" },
  { "sllha", "sllha" },
  { "type", "type" },
  { "uncertain", "uncertain" },
  { "utf8", "utf8" },
  { "var", "var" },
  { "varid", "varid" },
  { "zatu", "zatu" },
  { NULL, NULL },
};
struct xnn_attr asl_abases[] =
{
  { { "base",NULL } , { "base",NULL } },
  { { "bau",NULL } , { "bau",NULL } },
  { { "comment",NULL } , { "comment",NULL } },
  { { "deprecated",NULL } , { "deprecated",NULL } },
  { { "elles",NULL } , { "elles",NULL } },
  { { "hex",NULL } , { "hex",NULL } },
  { { "hzl",NULL } , { "hzl",NULL } },
  { { "id",NULL } , { "id",NULL } },
  { { "kw",NULL } , { "kw",NULL } },
  { { "kwu",NULL } , { "kwu",NULL } },
  { { "lak",NULL } , { "lak",NULL } },
  { { "lang",NULL } , { "lang",NULL } },
  { { "mzl",NULL } , { "mzl",NULL } },
  { { "n",NULL } , { "n",NULL } },
  { { "name",NULL } , { "name",NULL } },
  { { "o",NULL } , { "o",NULL } },
  { { "obzl",NULL } , { "obzl",NULL } },
  { { "ogsl",NULL } , { "ogsl",NULL } },
  { { "p",NULL } , { "p",NULL } },
  { { "project",NULL } , { "project",NULL } },
  { { "qm",NULL } , { "qm",NULL } },
  { { "qn",NULL } , { "qn",NULL } },
  { { "rec",NULL } , { "rec",NULL } },
  { { "ref",NULL } , { "ref",NULL } },
  { { "rsp",NULL } , { "rsp",NULL } },
  { { "sllha",NULL } , { "sllha",NULL } },
  { { "type",NULL } , { "type",NULL } },
  { { "uncertain",NULL } , { "uncertain",NULL } },
  { { "utf8",NULL } , { "utf8",NULL } },
  { { "var",NULL } , { "var",NULL } },
  { { "varid",NULL } , { "varid",NULL } },
  { { "zatu",NULL } , { "zatu",NULL } },
  { { NULL,NULL } , { NULL,NULL } },
};
struct xnn_xname asl_enames[] =
{
  { "sl:form", "http://oracc.org/ns/sl/1.0:form" },
  { "sl:inherited", "http://oracc.org/ns/sl/1.0:inherited" },
  { "sl:inote", "http://oracc.org/ns/sl/1.0:inote" },
  { "sl:iv", "http://oracc.org/ns/sl/1.0:iv" },
  { "sl:list", "http://oracc.org/ns/sl/1.0:list" },
  { "sl:note", "http://oracc.org/ns/sl/1.0:note" },
  { "sl:pname", "http://oracc.org/ns/sl/1.0:pname" },
  { "sl:proof", "http://oracc.org/ns/sl/1.0:proof" },
  { "sl:q", "http://oracc.org/ns/sl/1.0:q" },
  { "sl:qs", "http://oracc.org/ns/sl/1.0:qs" },
  { "sl:sign", "http://oracc.org/ns/sl/1.0:sign" },
  { "sl:signlist", "http://oracc.org/ns/sl/1.0:signlist" },
  { "sl:sort", "http://oracc.org/ns/sl/1.0:sort" },
  { "sl:uname", "http://oracc.org/ns/sl/1.0:uname" },
  { "sl:unote", "http://oracc.org/ns/sl/1.0:unote" },
  { "sl:uphase", "http://oracc.org/ns/sl/1.0:uphase" },
  { "sl:utf8", "http://oracc.org/ns/sl/1.0:utf8" },
  { "sl:v", "http://oracc.org/ns/sl/1.0:v" },
  { NULL, NULL },
};
struct xnn_data asl_data = { asl_enames, asl_anames, asl_nstab };
