#!/usr/bin/perl
use warnings; use strict; use open 'utf8';
use Getopt::Long;
use Pod::Usage;

my $atf = '';
my $otf = '';
my $project = '';

GetOptions(
    'atf:s'=>\$atf,
    'otf:s'=>\$otf,
    'project:s'=>\$project,
    );

open(O,">$otf");
print O <<EOF;
\@document

\@project $project

\@title Oracc Edition of $atf

\@section introduction

This PDF was generated by Oracc.

\@end section

\@newpage

\@section edition
    
\@atffile $atf

\@end section

\@end document

EOF

1;
