#line 2 "tg2-l.c"

#line 4 "tg2-l.c"

#define YY_NO_INPUT 1
#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer tg2_create_buffer
#define yy_delete_buffer tg2_delete_buffer
#define yy_scan_buffer tg2_scan_buffer
#define yy_scan_string tg2_scan_string
#define yy_scan_bytes tg2_scan_bytes
#define yy_init_buffer tg2_init_buffer
#define yy_flush_buffer tg2_flush_buffer
#define yy_load_buffer_state tg2_load_buffer_state
#define yy_switch_to_buffer tg2_switch_to_buffer
#define yypush_buffer_state tg2push_buffer_state
#define yypop_buffer_state tg2pop_buffer_state
#define yyensure_buffer_stack tg2ensure_buffer_stack
#define yy_flex_debug tg2_flex_debug
#define yyin tg2in
#define yyleng tg2leng
#define yylex tg2lex
#define yylineno tg2lineno
#define yyout tg2out
#define yyrestart tg2restart
#define yytext tg2text
#define yywrap tg2wrap
#define yyalloc tg2alloc
#define yyrealloc tg2realloc
#define yyfree tg2free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define tg2_create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer tg2_create_buffer
#endif

#ifdef yy_delete_buffer
#define tg2_delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer tg2_delete_buffer
#endif

#ifdef yy_scan_buffer
#define tg2_scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer tg2_scan_buffer
#endif

#ifdef yy_scan_string
#define tg2_scan_string_ALREADY_DEFINED
#else
#define yy_scan_string tg2_scan_string
#endif

#ifdef yy_scan_bytes
#define tg2_scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes tg2_scan_bytes
#endif

#ifdef yy_init_buffer
#define tg2_init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer tg2_init_buffer
#endif

#ifdef yy_flush_buffer
#define tg2_flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer tg2_flush_buffer
#endif

#ifdef yy_load_buffer_state
#define tg2_load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state tg2_load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define tg2_switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer tg2_switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define tg2push_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state tg2push_buffer_state
#endif

#ifdef yypop_buffer_state
#define tg2pop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state tg2pop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define tg2ensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack tg2ensure_buffer_stack
#endif

#ifdef yylex
#define tg2lex_ALREADY_DEFINED
#else
#define yylex tg2lex
#endif

#ifdef yyrestart
#define tg2restart_ALREADY_DEFINED
#else
#define yyrestart tg2restart
#endif

#ifdef yylex_init
#define tg2lex_init_ALREADY_DEFINED
#else
#define yylex_init tg2lex_init
#endif

#ifdef yylex_init_extra
#define tg2lex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra tg2lex_init_extra
#endif

#ifdef yylex_destroy
#define tg2lex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy tg2lex_destroy
#endif

#ifdef yyget_debug
#define tg2get_debug_ALREADY_DEFINED
#else
#define yyget_debug tg2get_debug
#endif

#ifdef yyset_debug
#define tg2set_debug_ALREADY_DEFINED
#else
#define yyset_debug tg2set_debug
#endif

#ifdef yyget_extra
#define tg2get_extra_ALREADY_DEFINED
#else
#define yyget_extra tg2get_extra
#endif

#ifdef yyset_extra
#define tg2set_extra_ALREADY_DEFINED
#else
#define yyset_extra tg2set_extra
#endif

#ifdef yyget_in
#define tg2get_in_ALREADY_DEFINED
#else
#define yyget_in tg2get_in
#endif

#ifdef yyset_in
#define tg2set_in_ALREADY_DEFINED
#else
#define yyset_in tg2set_in
#endif

#ifdef yyget_out
#define tg2get_out_ALREADY_DEFINED
#else
#define yyget_out tg2get_out
#endif

#ifdef yyset_out
#define tg2set_out_ALREADY_DEFINED
#else
#define yyset_out tg2set_out
#endif

#ifdef yyget_leng
#define tg2get_leng_ALREADY_DEFINED
#else
#define yyget_leng tg2get_leng
#endif

#ifdef yyget_text
#define tg2get_text_ALREADY_DEFINED
#else
#define yyget_text tg2get_text
#endif

#ifdef yyget_lineno
#define tg2get_lineno_ALREADY_DEFINED
#else
#define yyget_lineno tg2get_lineno
#endif

#ifdef yyset_lineno
#define tg2set_lineno_ALREADY_DEFINED
#else
#define yyset_lineno tg2set_lineno
#endif

#ifdef yywrap
#define tg2wrap_ALREADY_DEFINED
#else
#define yywrap tg2wrap
#endif

#ifdef yyalloc
#define tg2alloc_ALREADY_DEFINED
#else
#define yyalloc tg2alloc
#endif

#ifdef yyrealloc
#define tg2realloc_ALREADY_DEFINED
#else
#define yyrealloc tg2realloc
#endif

#ifdef yyfree
#define tg2free_ALREADY_DEFINED
#else
#define yyfree tg2free
#endif

#ifdef yytext
#define tg2text_ALREADY_DEFINED
#else
#define yytext tg2text
#endif

#ifdef yyleng
#define tg2leng_ALREADY_DEFINED
#else
#define yyleng tg2leng
#endif

#ifdef yyin
#define tg2in_ALREADY_DEFINED
#else
#define yyin tg2in
#endif

#ifdef yyout
#define tg2out_ALREADY_DEFINED
#else
#define yyout tg2out
#endif

#ifdef yy_flex_debug
#define tg2_flex_debug_ALREADY_DEFINED
#else
#define yy_flex_debug tg2_flex_debug
#endif

#ifdef yylineno
#define tg2lineno_ALREADY_DEFINED
#else
#define yylineno tg2lineno
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define tg2wrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 111
#define YY_END_OF_BUFFER 112
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[414] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   42,   42,    0,    0,
        0,    0,  108,  108,    0,    0,  112,  109,  110,   41,
       18,   31,  109,   45,  111,    2,   45,   55,  111,   55,
      111,   61,  111,    3,   61,   58,   63,   33,   33,    1,
       34,   36,   35,   38,  111,    1,   88,    5,   77,    4,
      111,  111,   77,  111,  111,  111,   77,   87,    5,   85,
       83,   84,   86,   89,    9,   11,    7,    6,   21,   21,

       42,  111,  111,  108,  106,    0,   31,   32,  107,   43,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,   47,   47,   46,   55,
       55,   54,    0,    0,   50,   50,   50,   53,   51,   52,
       61,   61,    0,    0,   60,   61,   59,   58,   57,   63,
       56,   62,   33,   33,   34,   36,   35,   38,   38,   37,
        0,   39,   88,   88,   77,   77,   75,   75,   73,   69,
       76,   72,   71,   70,   87,   87,   89,   89,    9,    9,
       11,   11,    7,    6,    6,    0,    0,   42,    0,  101,
      108,  106,    0,   32,  107,   43,  107,  107,  107,  107,

      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,   54,    0,   50,   50,   52,    0,   60,
       62,   75,   74,   73,   69,   76,   72,   71,   70,    0,
        0,   95,  101,    0,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,   40,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,   74,    0,    0,   23,  107,  107,
      107,   92,   13,  107,  107,  107,  107,  107,  107,   40,
      107,  107,  107,  107,  107,  107,  107,  100,  107,  107,

      107,  107,  107,  107,  107,  107,  107,  107,  107,   22,
        0,    0,  107,  107,   49,  107,   90,  107,    0,    0,
      107,  107,   67,  107,   17,  107,  107,  107,   10,   12,
       98,  107,  107,   64,  107,  107,  107,  104,  107,  107,
       65,  107,  107,  107,    0,    0,   29,   44,   49,   48,
       93,   91,    0,    0,   24,  107,  107,   94,   68,  107,
       96,   97,   99,   30,  107,  103,  107,  107,  107,   80,
      107,  107,   78,   66,  107,   19,   20,   48,   48,    0,
        0,   25,   26,  107,  105,  107,  107,  107,  107,   81,
       82,  107,   48,    0,    0,   27,  105,  107,    8,  107,

      107,  107,   28,    0,  102,   14,  107,  107,   28,   79,
       15,   16,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    1,    5,    6,    7,    1,    1,    8,
        1,    9,   10,   11,   12,   13,   14,    1,   15,    1,
        1,    1,    1,    1,    1,   16,    1,    1,   17,    1,
       18,   19,    1,   20,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       22,    1,   23,    1,   24,    1,   25,   26,   27,   28,

       29,   30,   31,   32,   33,   34,    1,   35,   36,   37,
       38,   39,   40,   41,   42,   43,   44,   45,   46,    1,
       47,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[48] =
    {   0,
        1,    2,    3,    1,    1,    1,    1,    1,    1,    1,
        4,    1,    1,    1,    1,    1,    5,    6,    1,    1,
        1,    7,    8,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[465] =
    {   0,
      983,    0,    4,    6,    0,    0,   11,   14,   24,   31,
       27,   34,   20,   22,   44,   49,   51,   56,   57,   75,
       83,   94,   66,   70,   72,   89,   91,  100,  982,  981,
      106,  108,   35,   41,    0,    0,  980,  979,  974,  973,
      941,  940,  974,  973,  110,  112,  975,  987,  987,  928,
      987,   68,   96,  971,  987,  987,  970,   96,  126,  128,
      138,  969,  130,  987,    0,  142,  146,    0,   98,  987,
      987,  968,    0,  116,  148,  987,  967,  987,  966,  987,
      962,    0,  964,    0,    0,    0,  963,  962,  961,  987,
      987,  987,  987,  960,  959,  958,    0,  957,  987,  117,

        0,    0,    0,    0,    0,  926,  955,  954,  953,  150,
      152,  155,  156,  158,  159,    2,  154,  160,   81,  165,
      162,  176,  175,  163,  164,  166,  952,  951,  950,  168,
      171,  181,  167,  183,  207,  208,  949,  216,  987,  948,
      947,  946,  205,  218,  170,  212,  987,  224,  987,  225,
      987,  945,    0,  210,  987,  944,    0,  227,  234,  987,
      236,  987,  943,  942,  941,  940,  939,  938,  937,  936,
      935,  934,  933,  932,  931,  930,  929,  928,  927,  926,
      925,  924,    0,  923,  922,  886,  893,    0,  919,  918,
        0,    0,  872,  916,  915,  914,  229,  232,  239,  238,

      241,  242,  243,  244,  246,  245,   63,  251,  248,  254,
      247,  249,  253,  252,  256,  255,  257,  250,  258,  261,
      268,  275,  259,  987,  265,  267,  913,  912,  270,  911,
      910,  909,  908,  907,  906,  905,  904,  903,  902,  860,
      865,  899,  898,  897,  280,  297,  299,  896,  895,  301,
      300,  894,  302,  305,  306,  893,  307,  310,  308,  311,
      309,  312,  318,  892,  313,  315,  321,  316,  314,  317,
      319,  322,  320,  891,  890,  850,  848,  887,  323,  324,
      327,  886,  885,  328,  329,  330,  331,  332,  369,  884,
      883,  335,  347,  351,  882,  881,  360,  880,  361,  879,

      366,  365,  372,  373,  378,  878,  380,  381,  382,  877,
      831,  848,  874,  873,  379,  872,  871,  870,  834,  841,
      383,  867,  866,  860,  852,  384,  844,  843,  836,  828,
      827,  820,  819,  812,  387,  804,  386,  796,  389,  395,
      788,  396,  780,  392,  772,  764,  756,  748,  397,  747,
      740,  739,  691,  696,  724,  716,  403,  715,  708,  400,
      707,  700,  692,  677,  404,  671,  408,  413,  409,  665,
      663,  657,  656,  655,  414,  647,  641,  639,  634,  592,
      583,  622,  456,  455,  454,  415,  451,  416,  417,  450,
      448,  424,  447,  401,  417,  442,  440,  439,  438,  435,

      418,  431,  434,  393,  432,  430,  428,  191,  172,  987,
       74,   13,  987,  462,  470,  478,  486,  494,  502,  510,
      518,  526,  534,  542,  550,  558,  566,  574,  582,  590,
      598,  606,  614,  622,  630,  638,  646,  654,  662,  670,
      676,  683,  691,  699,  707,  715,  723,  731,  739,  747,
      755,  763,  771,  779,  787,  795,  803,  811,  819,  827,
      835,  843,  851,  859
    } ;

static const flex_int16_t yy_def[465] =
    {   0,
      414,  414,  415,  415,  416,  416,  417,  417,  418,  418,
      419,  419,  420,  420,  421,  421,  422,  422,  423,  423,
      424,  424,  425,  425,  426,  426,  427,  427,  428,  428,
      429,  429,  430,  430,  416,  416,  431,  431,  416,  416,
      416,  416,  432,  432,  433,  433,  413,  413,  413,  413,
      413,  413,  434,  435,  413,  413,  413,  436,  413,  437,
      413,  438,  413,  413,  439,  413,  413,  440,  440,  413,
      413,  413,  441,  442,  413,  413,  443,  413,  444,  413,
      445,  446,  447,  448,  449,  450,  451,  452,  452,  413,
      413,  413,  413,  453,  454,  455,  456,  457,  413,  413,

      458,  459,  460,  461,  462,  413,  413,  413,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  435,  413,  413,  436,
      413,  436,  413,  413,  437,  437,  463,  413,  413,  413,
      438,  413,  413,  413,  439,  413,  413,  413,  413,  413,
      413,  413,  440,  440,  413,  413,  441,  442,  413,  413,
      413,  413,  443,  413,  444,  413,  445,  464,  446,  447,
      448,  449,  450,  451,  452,  413,  453,  413,  454,  413,
      455,  413,  456,  457,  413,  413,  413,  458,  459,  460,
      461,  462,  413,  413,  413,  413,  434,  434,  434,  434,

      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  464,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  413,  413,  413,  413,  434,  434,
      434,  413,  413,  434,  434,  413,  434,  434,  434,  413,
      434,  434,  434,  434,  434,  434,  434,  413,  434,  434,

      434,  434,  434,  434,  434,  434,  434,  434,  434,  413,
      413,  413,  434,  434,  434,  434,  413,  434,  413,  413,
      434,  434,  413,  434,  413,  434,  434,  434,  413,  413,
      413,  434,  434,  413,  434,  434,  434,  413,  434,  434,
      413,  434,  434,  434,  413,  413,  413,  413,  413,  434,
      413,  413,  413,  413,  413,  434,  434,  413,  413,  434,
      413,  413,  413,  413,  434,  413,  434,  434,  434,  413,
      434,  434,  434,  413,  434,  413,  413,  413,  413,  413,
      413,  413,  413,  434,  434,  434,  434,  434,  434,  413,
      413,  434,  413,  413,  413,  413,  413,  434,  413,  434,

      434,  434,  413,  413,  413,  413,  434,  434,  413,  413,
      413,  413,    0,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413
    } ;

static const flex_int16_t yy_nxt[1035] =
    {   0,
      413,  146,   49,  195,   50,   55,   56,   55,   56,   51,
      147,   51,   59,   56,  412,   59,   56,   60,   52,   53,
       60,   57,   70,   57,   70,   63,   64,   61,   69,   70,
       61,   65,   63,   64,   66,   69,   70,   55,   65,  205,
       67,   66,   72,   55,   72,   75,   76,   67,   71,   72,
       75,   76,   55,   78,  100,   71,   72,   55,   78,   80,
      100,   81,   82,   83,  195,   84,   85,   55,   78,  107,
       86,   55,   78,   55,   55,  411,   87,   80,  257,   81,
       82,   83,  195,   84,   85,   89,  108,   90,   86,   91,
       55,   55,   55,   55,   87,   92,   89,  131,   90,  154,

       91,   55,   55,  132,   93,  210,   92,   55,   56,   55,
       56,   55,   55,   55,   55,   93,  110,  159,  160,  155,
      111,  112,  113,  114,  115,  116,  117,  133,  118,  131,
      119,  143,  120,  121,  122,  136,  123,  124,  125,  138,
      139,  126,  134,  148,  137,  186,  144,  150,  151,  161,
      162,  196,  149,  195,  140,  195,  195,  195,  187,  195,
      195,  195,  152,  195,  195,  195,  195,  195,  133,  131,
      110,  230,  131,  409,  207,  132,  195,  195,  224,  198,
      413,  200,  131,  134,  225,  139,  197,  199,  132,  211,
      202,  220,  412,  201,  213,  203,  208,  223,  204,  206,

      214,  209,  212,  218,  222,  221,  143,  215,  226,  226,
      216,  154,  219,  146,  136,  136,  217,  138,  139,  229,
      151,  144,  147,  137,  137,  148,  150,  151,  159,  160,
      195,  155,  140,  195,  149,  159,  160,  161,  162,  195,
      195,  152,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  245,  195,  246,  248,  249,  225,  139,  226,  195,
      252,  229,  151,  247,  224,  250,  195,  258,  267,  256,
      264,  195,  262,  251,  269,  253,  255,  254,  259,  260,
      261,  263,  265,  266,  268,  270,  272,  271,  195,  273,

      195,  195,  195,  195,  279,  274,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  285,  281,  195,  195,
      317,  286,  195,  195,  280,  284,  195,  288,  305,  295,
      296,  289,  287,  291,  292,  294,  297,  301,  195,  303,
      293,  300,  195,  302,  304,  299,  309,  308,  319,  306,
      307,  331,  195,  318,  313,  316,  195,  195,  315,  314,
      323,  320,  324,  195,  338,  327,  322,  321,  326,  195,
      349,  195,  195,  195,  355,  195,  356,  195,  195,  328,
      195,  357,  336,  195,  332,  350,  195,  370,  349,  371,

      337,  195,  333,  335,  383,  195,  384,  339,  342,  195,
      195,  360,  367,  378,  195,  195,  195,  195,  195,  195,
      340,  368,  343,  344,  365,  195,  375,  369,  385,  411,
      372,  406,  195,  405,  410,  409,  406,  373,  392,  399,
      405,  397,  398,  396,  386,  404,  389,  403,  393,  391,
      387,  390,  399,  401,  388,  397,  396,  383,  400,  407,
      402,  408,   48,   48,   48,   48,   48,   48,   48,   48,
       54,   54,   54,   54,   54,   54,   54,   54,   55,   55,
       55,   55,   55,   55,   55,   55,   58,   58,   58,   58,
       58,   58,   58,   58,   62,   62,   62,   62,   62,   62,

       62,   62,   68,   68,   68,   68,   68,   68,   68,   68,
       73,   73,   73,   73,   73,   73,   73,   73,   74,   74,
       74,   74,   74,   74,   74,   74,   77,   77,   77,   77,
       77,   77,   77,   77,   79,   79,   79,   79,   79,   79,
       79,   79,   88,   88,   88,   88,   88,   88,   88,   88,
       94,   94,   94,   94,   94,   94,   94,   94,   95,   95,
       95,   95,   95,   95,   95,   95,   96,   96,   96,   96,
       96,   96,   96,   96,   97,   97,   97,   97,   97,   97,
       97,   97,   98,   98,   98,   98,   98,   98,   98,   98,
       99,   99,   99,   99,   99,   99,   99,   99,  101,  101,

      101,  101,  101,  101,  101,  101,  104,  104,  104,  104,
      104,  104,  104,  104,  105,  105,  105,  105,  105,  105,
      105,  105,  109,  382,  395,  109,  109,  109,  109,  109,
      127,  127,  394,  127,  127,  379,  127,  127,  130,  130,
      393,  130,  377,  130,  130,  130,  135,  135,  376,  135,
      135,  135,  135,  135,  141,  141,  374,  195,  391,  141,
      141,  141,  145,  145,  390,  145,  370,  145,  145,  145,
      153,  153,  366,  153,  153,  153,  157,  157,  364,  157,
      157,  157,  157,  158,  158,  158,  158,  158,  158,  158,
      158,  163,  163,  363,  163,  163,  163,  163,  163,  165,

      165,  362,  165,  165,  165,  165,  165,  167,  361,  359,
      167,  167,  167,  167,  167,  169,  358,  382,  169,  169,
      169,  169,  169,  170,  170,  355,  170,  170,  170,  170,
      170,  171,  381,  380,  171,  171,  171,  171,  171,  172,
      352,  351,  172,  172,  172,  172,  172,  173,  379,  348,
      173,  173,  173,  173,  173,  174,  174,  347,  174,  174,
      174,  174,  174,  175,  175,  377,  175,  175,  175,  175,
      175,  177,  177,  376,  177,  177,  177,  177,  177,  179,
      179,  374,  179,  179,  179,  179,  179,  181,  181,  341,
      181,  181,  181,  181,  181,  183,  183,  338,  183,  183,

      183,  183,  183,  184,  184,  366,  184,  184,  184,  184,
      184,  188,  188,  334,  188,  188,  188,  188,  188,  189,
      364,  363,  189,  189,  189,  189,  189,  190,  331,  330,
      190,  190,  190,  190,  190,  191,  191,  329,  191,  191,
      191,  191,  191,  192,  362,  361,  192,  192,  192,  192,
      192,  137,  137,  325,  137,  137,  137,  137,  137,  233,
      233,  359,  233,  233,  233,  233,  233,  323,  358,  354,
      353,  352,  317,  351,  348,  347,  346,  345,  310,  341,
      334,  298,  330,  329,  325,  290,  283,  282,  278,  312,
      311,  275,  310,  298,  290,  286,  283,  282,  278,  243,

      242,  277,  276,  239,  238,  237,  236,  235,  234,  275,
      232,  231,  230,  228,  227,  196,  195,  194,  244,  243,
      242,  241,  240,  185,  185,  182,  182,  180,  180,  178,
      178,  176,  176,  239,  238,  237,  236,  235,  234,  232,
      232,  166,  166,  164,  164,  156,  231,  142,  142,  228,
      227,  129,  128,  128,  195,  194,  107,  193,  185,  182,
      180,  178,  176,  176,  166,  166,  168,  166,  164,  156,
      142,  129,  128,  106,  413,   56,   56,  103,  103,  102,
      102,   55,   55,   56,   56,   49,   47,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,

      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413
    } ;

static const flex_int16_t yy_chk[1035] =
    {   0,
        0,   65,    2,  116,    2,    3,    3,    4,    4,    2,
       65,    2,    7,    7,  412,    8,    8,    7,    2,    2,
        8,    3,   13,    4,   14,    9,    9,    7,   11,   11,
        8,    9,   10,   10,    9,   12,   12,   33,   10,  116,
        9,   10,   13,   34,   14,   15,   15,   10,   11,   11,
       16,   16,   17,   17,   33,   12,   12,   18,   18,   19,
       34,   19,   19,   19,  207,   19,   19,   23,   23,   52,
       19,   24,   24,   25,   25,  411,   19,   20,  207,   20,
       20,   20,  119,   20,   20,   21,   52,   21,   20,   21,
       26,   26,   27,   27,   20,   21,   22,   58,   22,   69,

       22,   28,   28,   58,   21,  119,   22,   31,   31,   32,
       32,   45,   45,   46,   46,   22,   53,   74,   74,   69,
       53,   53,   53,   53,   53,   53,   53,   59,   53,   60,
       53,   63,   53,   53,   53,   60,   53,   53,   53,   61,
       61,   53,   59,   66,   60,  100,   63,   67,   67,   75,
       75,  110,   66,  111,   61,  117,  112,  113,  100,  114,
      115,  118,   67,  121,  124,  125,  120,  126,  133,  130,
      110,  145,  131,  409,  118,  130,  123,  122,  131,  112,
      145,  113,  132,  133,  134,  134,  111,  112,  132,  120,
      114,  124,  408,  113,  121,  115,  118,  126,  115,  117,

      122,  118,  120,  123,  125,  124,  143,  122,  135,  136,
      122,  154,  123,  146,  135,  136,  122,  138,  138,  144,
      144,  143,  146,  135,  136,  148,  150,  150,  158,  158,
      197,  154,  138,  198,  148,  159,  159,  161,  161,  200,
      199,  150,  201,  202,  203,  204,  206,  205,  211,  209,
      212,  218,  208,  214,  213,  210,  216,  215,  217,  219,
      223,  197,  220,  197,  199,  200,  225,  225,  226,  221,
      203,  229,  229,  198,  226,  201,  222,  208,  216,  206,
      213,  245,  211,  202,  218,  203,  205,  204,  208,  209,
      210,  212,  214,  215,  217,  219,  221,  220,  246,  222,

      247,  251,  250,  253,  245,  223,  254,  255,  257,  259,
      261,  258,  260,  262,  265,  269,  266,  268,  270,  263,
      271,  273,  267,  272,  279,  280,  251,  247,  281,  284,
      285,  286,  287,  288,  246,  250,  292,  254,  269,  261,
      262,  255,  253,  257,  258,  260,  263,  267,  293,  268,
      259,  266,  294,  267,  268,  265,  273,  272,  286,  270,
      271,  297,  299,  285,  279,  284,  302,  301,  281,  280,
      289,  286,  289,  303,  304,  293,  288,  287,  292,  305,
      315,  307,  308,  309,  321,  326,  321,  337,  335,  294,
      339,  321,  302,  344,  297,  315,  340,  342,  349,  342,

      303,  360,  299,  301,  357,  365,  357,  304,  307,  367,
      369,  326,  337,  349,  368,  375,  386,  388,  389,  401,
      305,  339,  308,  309,  335,  392,  344,  340,  360,  407,
      342,  406,  402,  405,  404,  403,  400,  342,  375,  399,
      398,  397,  386,  396,  365,  395,  369,  394,  393,  391,
      367,  390,  387,  389,  368,  385,  384,  383,  388,  401,
      392,  402,  414,  414,  414,  414,  414,  414,  414,  414,
      415,  415,  415,  415,  415,  415,  415,  415,  416,  416,
      416,  416,  416,  416,  416,  416,  417,  417,  417,  417,
      417,  417,  417,  417,  418,  418,  418,  418,  418,  418,

      418,  418,  419,  419,  419,  419,  419,  419,  419,  419,
      420,  420,  420,  420,  420,  420,  420,  420,  421,  421,
      421,  421,  421,  421,  421,  421,  422,  422,  422,  422,
      422,  422,  422,  422,  423,  423,  423,  423,  423,  423,
      423,  423,  424,  424,  424,  424,  424,  424,  424,  424,
      425,  425,  425,  425,  425,  425,  425,  425,  426,  426,
      426,  426,  426,  426,  426,  426,  427,  427,  427,  427,
      427,  427,  427,  427,  428,  428,  428,  428,  428,  428,
      428,  428,  429,  429,  429,  429,  429,  429,  429,  429,
      430,  430,  430,  430,  430,  430,  430,  430,  431,  431,

      431,  431,  431,  431,  431,  431,  432,  432,  432,  432,
      432,  432,  432,  432,  433,  433,  433,  433,  433,  433,
      433,  433,  434,  382,  381,  434,  434,  434,  434,  434,
      435,  435,  380,  435,  435,  379,  435,  435,  436,  436,
      378,  436,  377,  436,  436,  436,  437,  437,  376,  437,
      437,  437,  437,  437,  438,  438,  374,  373,  372,  438,
      438,  438,  439,  439,  371,  439,  370,  439,  439,  439,
      440,  440,  366,  440,  440,  440,  441,  441,  364,  441,
      441,  441,  441,  442,  442,  442,  442,  442,  442,  442,
      442,  443,  443,  363,  443,  443,  443,  443,  443,  444,

      444,  362,  444,  444,  444,  444,  444,  445,  361,  359,
      445,  445,  445,  445,  445,  446,  358,  356,  446,  446,
      446,  446,  446,  447,  447,  355,  447,  447,  447,  447,
      447,  448,  354,  353,  448,  448,  448,  448,  448,  449,
      352,  351,  449,  449,  449,  449,  449,  450,  350,  348,
      450,  450,  450,  450,  450,  451,  451,  347,  451,  451,
      451,  451,  451,  452,  452,  346,  452,  452,  452,  452,
      452,  453,  453,  345,  453,  453,  453,  453,  453,  454,
      454,  343,  454,  454,  454,  454,  454,  455,  455,  341,
      455,  455,  455,  455,  455,  456,  456,  338,  456,  456,

      456,  456,  456,  457,  457,  336,  457,  457,  457,  457,
      457,  458,  458,  334,  458,  458,  458,  458,  458,  459,
      333,  332,  459,  459,  459,  459,  459,  460,  331,  330,
      460,  460,  460,  460,  460,  461,  461,  329,  461,  461,
      461,  461,  461,  462,  328,  327,  462,  462,  462,  462,
      462,  463,  463,  325,  463,  463,  463,  463,  463,  464,
      464,  324,  464,  464,  464,  464,  464,  323,  322,  320,
      319,  318,  317,  316,  314,  313,  312,  311,  310,  306,
      300,  298,  296,  295,  291,  290,  283,  282,  278,  277,
      276,  275,  274,  264,  256,  252,  249,  248,  244,  243,

      242,  241,  240,  239,  238,  237,  236,  235,  234,  233,
      232,  231,  230,  228,  227,  196,  195,  194,  193,  190,
      189,  187,  186,  185,  184,  182,  181,  180,  179,  178,
      177,  176,  175,  174,  173,  172,  171,  170,  169,  168,
      167,  166,  165,  164,  163,  156,  152,  142,  141,  140,
      137,  129,  128,  127,  109,  108,  107,  106,   98,   96,
       95,   94,   89,   88,   87,   83,   81,   79,   77,   72,
       62,   57,   54,   50,   47,   44,   43,   42,   41,   40,
       39,   38,   37,   30,   29,    1,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,

      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[112] =
    {   0,
1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "tg2.l"
#line 5 "tg2.l"

#include <ctype128.h>
#include "grammar.h"
#include "gx.h"
#include "tg2.tab.h"
#include "rnvtgi.h"
#include "npool.h"
#define YY_NO_UNISTD_H

#define yylloc tg2lloc
#define yylval tg2lval

#define dup(s) yylval.text = (char*)npool_copy((unsigned char *)(s),curr_cbd->pool)
#define ytdup() (yylval.text = (char*)npool_copy((ucp)unspace(yytext),curr_cbd->pool))
#define ytdupn(n) yylval.text = (char*)npool_copy((ucp)unspace(yytext+(n)),curr_cbd->pool)
#define yi(tok) yylval.i = tok;
#define yln(s) if (ylntrace) {fprintf(stderr, "%s: %d\n",(s),yylineno);}

static int after_xENTSNS = 0;
static int after_xGW = 0;
static int after_xPOS = 0;
static int after_xLANG = 0;
static int after_xRENMRG = 0;
static int xdisc = 0, xdiscl = 0;
static int yycolumn = 0;
extern char *efile;

extern int bang, star;
extern List *cmt_queue;

static void baseco(const char *type);
static void basesc(const char *type);

static char *b_alt_tok = NULL;
static void alt_wrapup(int clean);
static void clean_alt_paren(void);
static char *unspace(char*s);
static void gx_user_action(void);
#define mtch(x) fprintf(stderr,"matched %s",(x))

#define YY_USER_ACTION gx_user_action();

/* tg2 uses the tg1 globals */
extern int ylntrace;
extern int flextrace;
extern int mystate;
#define ss(arg) (mystate=arg)

char *ssnames2[] = {
"0", "xALLOW", "xB", "xBP", "xB",
"xCF", "xGW", "xPOS", "xSPOS",
"xF", "xS", "xSW",
"xPROJ", "xLANG", "xTEXT", "xWORD", "xENTSNS", "xWHY",
"xCOMMENT", "xELANG", "xOID", "xFLUSH", "xINCL", 
};

#define MAX_INCLUDE_DEPTH 10
struct bufstack
{
  char *file;
  int line;
  FILE *fp;
  YY_BUFFER_STATE yycb;
};
extern struct bufstack include_stack[MAX_INCLUDE_DEPTH];
extern int include_stack_ptr;
static void includec(void);
static void includeo(char *file);

#line 1179 "tg2-l.c"

#line 1181 "tg2-l.c"

#define INITIAL 0
#define xALLOW 1
#define xB 2
#define xBP 3
#define xBA 4
#define xCF 5
#define xGW 6
#define xPOS 7
#define xSPOS 8
#define xF 9
#define xS 10
#define xSW 11
#define xPROJ 12
#define xLANG 13
#define xTEXT 14
#define xWORD 15
#define xENTSNS 16
#define xWHY 17
#define xCOMMENT 18
#define xELANG 19
#define xOID 20
#define xFLUSH 21
#define xINCL 22

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 83 "tg2.l"


#line 1426 "tg2-l.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 414 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 413 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 85 "tg2.l"
{ BEGIN ss(0); yycolumn = 1; return EOL; }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 86 "tg2.l"
{ BEGIN ss(0); yycolumn = 1; }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 87 "tg2.l"
{ BEGIN ss(0); yycolumn = 1; if (b_alt_tok) { alt_wrapup(1); return(BASE_ALT); } }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 88 "tg2.l"
{ BEGIN ss(0); yycolumn = 1; return(END_FORM); }
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 89 "tg2.l"
{ BEGIN ss(0); yycolumn = 1; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 91 "tg2.l"
{ ytdup(); return(WORDSPEC); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 92 "tg2.l"
{ ytdup(); return(TEXTSPEC); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 93 "tg2.l"
{ yln("@project"); BEGIN xPROJ; return PROJECT; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 94 "tg2.l"
{ BEGIN ss(0); ytdup(); return PROJSPEC; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 95 "tg2.l"
{ BEGIN ss(xLANG); after_xLANG = 0; return LANG; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 96 "tg2.l"
{ BEGIN ss(after_xLANG); ytdup(); return LANGSPEC; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 97 "tg2.l"
{ BEGIN ss(xTEXT); return NAME; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 98 "tg2.l"
{ BEGIN ss(xWORD); return CBD; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 99 "tg2.l"
{ BEGIN ss(xTEXT); return PROPS; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 100 "tg2.l"
{ BEGIN ss(xTEXT); return RELDEF; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 101 "tg2.l"
{ BEGIN ss(xLANG); after_xLANG = 0; return TRANSLANG; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 102 "tg2.l"
{ BEGIN ss(xTEXT); return I18N; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 104 "tg2.l"
{ BEGIN ss(xENTSNS); return yytext[0]; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 105 "tg2.l"
{ BEGIN ss(after_xENTSNS); return(ENTRY); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 106 "tg2.l"
{ BEGIN ss(after_xENTSNS); return(SENSE); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 107 "tg2.l"
{ BEGIN ss(0); yyless(0); /* should error */ }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 109 "tg2.l"
{ BEGIN ss(xTEXT); return(WHY); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 110 "tg2.l"
{ vyyerror(yylloc,"use #why not @why in version 2 glossary\n", NULL); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 112 "tg2.l"
{ yln("@entry"); BEGIN ss(xCF); after_xRENMRG = after_xENTSNS = xCF; after_xGW = xPOS; after_xPOS = 0; xdisc = EDISC; xdiscl = EDISCL; return(ENTRY); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 113 "tg2.l"
{ yln("@entry"); BEGIN ss(xCF); bang = 1; after_xRENMRG = after_xENTSNS = xCF; after_xGW = xPOS; after_xPOS = 0; xdisc = EDISC; xdiscl = EDISCL; return(ENTRY); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 114 "tg2.l"
{ yln("@entry"); BEGIN ss(xCF); star = 1; after_xRENMRG = after_xENTSNS = xCF; after_xGW = xPOS; after_xPOS = 0; xdisc = EDISC; xdiscl = EDISCL; return(ENTRY); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 115 "tg2.l"
{ yln("@entry"); BEGIN ss(xCF); bang = star = 1; after_xRENMRG = after_xENTSNS = xCF; after_xGW = xPOS; after_xPOS = 0; xdisc = EDISC; xdiscl = EDISCL; return(ENTRY); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 116 "tg2.l"
{ yln("@endentry"); BEGIN ss(0); return(END_ENTRY); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 118 "tg2.l"
{ BEGIN ss(xCF); after_xPOS = 0; return(ALIAS); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 120 "tg2.l"
{ BEGIN ss(xCF); after_xPOS = xCF; return(PARTS); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 122 "tg2.l"
{ BEGIN ss(after_xRENMRG); return(RENAME); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 123 "tg2.l"
{ BEGIN ss(after_xRENMRG); return(MERGE); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 125 "tg2.l"
{ dup(unspace(yytext)); return(CF); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 126 "tg2.l"
{ BEGIN ss(xGW); return(yytext[yyleng-1]); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 127 "tg2.l"
{ ytdup(); return(GW); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 128 "tg2.l"
{ BEGIN ss(after_xGW); return(yytext[0]); }
	YY_BREAK
case 37:
/* rule 37 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 129 "tg2.l"
{ BEGIN ss(0); ytdup(); return(POS); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 130 "tg2.l"
{ BEGIN ss(after_xPOS); ytdup(); return(POS); }
	YY_BREAK
case 39:
/* rule 39 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 131 "tg2.l"
{ BEGIN ss(0); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 133 "tg2.l"
{ BEGIN ss(xLANG); after_xLANG = xTEXT; return GWL; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 135 "tg2.l"
{ BEGIN ss(xCOMMENT); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 136 "tg2.l"
{ BEGIN ss(0); bld_cmt_queue(&yylloc, (ucp)ytdup()); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 137 "tg2.l"
{ BEGIN ss(xTEXT); ytdupn(1); return(DCF); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 139 "tg2.l"
{ BEGIN ss(xALLOW); return(ALLOW); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 140 "tg2.l"
{ ytdup(); return(BASE_PRI); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 141 "tg2.l"
{ return(yytext[0]); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 142 "tg2.l"
{ ytdup(); return(BASE_PRI); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 144 "tg2.l"
{ BEGIN ss(xBP); basesc("initial"); return(BASES); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 145 "tg2.l"
{ BEGIN ss(xBP); return(BASES); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 146 "tg2.l"
{ ytdupn(1); return(LANGSPEC); }
	YY_BREAK
case 51:
/* rule 51 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 147 "tg2.l"
{ BEGIN ss(0); yycolumn = 1; basesc("final"); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 148 "tg2.l"
{ BEGIN ss(xBP); basesc("double"); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 149 "tg2.l"
{ BEGIN ss(xBP); }
	YY_BREAK
case 54:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 150 "tg2.l"
{ BEGIN ss(xBA); ytdup(); return(BASE_PRI); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 151 "tg2.l"
{ ytdup(); return(BASE_PRI); }
	YY_BREAK
case 56:
/* rule 56 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 152 "tg2.l"
{ BEGIN ss(0); yycolumn = 1; basesc("final"); if (b_alt_tok) { alt_wrapup(1); return(BASE_ALT); } }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 153 "tg2.l"
{ baseco("double"); unput(','); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 154 "tg2.l"
{ if (b_alt_tok) { alt_wrapup(0); return(BASE_ALT); } }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 155 "tg2.l"
{ baseco("initial"); unput('('); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 156 "tg2.l"
{ b_alt_tok = strdup(yytext+1); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 157 "tg2.l"
{ b_alt_tok = strdup(yytext); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 158 "tg2.l"
{ BEGIN ss(xBP); basesc("double"); if (b_alt_tok) { alt_wrapup(1); return(BASE_ALT); } }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 159 "tg2.l"
{ BEGIN ss(xBP); if (b_alt_tok) { alt_wrapup(1); return(BASE_ALT); } }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 161 "tg2.l"
{ BEGIN ss(xTEXT); return(PHON); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 162 "tg2.l"
{ BEGIN ss(xTEXT); return(ROOT); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 163 "tg2.l"
{ BEGIN ss(xWORD); return(STEM); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 165 "tg2.l"
{ BEGIN ss(xF); return(FORM); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 166 "tg2.l"
{ BEGIN ss(xF); bang = 1; return(FORM); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 167 "tg2.l"
{ ytdupn(1); return(FLANG); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 168 "tg2.l"
{ ytdupn(1); return(FRWS); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 169 "tg2.l"
{ ytdupn(1); return(FBASE); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 170 "tg2.l"
{ ytdupn(1); return(FCONT); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 171 "tg2.l"
{ ytdupn(1); return(FNORM); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 172 "tg2.l"
{ ytdupn(2); return(FMORPH2); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 173 "tg2.l"
{ ytdupn(1); return(FMORPH); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 174 "tg2.l"
{ ytdupn(1); return(FSTEM); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 175 "tg2.l"
{ ytdup(); return(FFORM); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 177 "tg2.l"
{ return(SENSES); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 178 "tg2.l"
{ return(END_SENSES); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 179 "tg2.l"
{ BEGIN ss(xS); after_xRENMRG = after_xENTSNS = after_xGW = xSPOS; xdisc = SDISC; return(SENSE); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 180 "tg2.l"
{ BEGIN ss(xS); bang = 1; after_xRENMRG = after_xENTSNS = after_xGW = xSPOS; xdisc = SDISC; return(SENSE); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 181 "tg2.l"
{ BEGIN ss(xS); after_xRENMRG = after_xENTSNS = after_xGW = xSPOS; xdisc = xdiscl = SDISCL; return(SENSE); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 182 "tg2.l"
{ BEGIN ss(xSW); return(yytext[0]); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 183 "tg2.l"
{ BEGIN ss(xSW); return(yytext[0]); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 184 "tg2.l"
{ BEGIN ss(xSW); return(yytext[0]); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 185 "tg2.l"
{ BEGIN ss(xGW); return(yytext[0]); }
	YY_BREAK
case 87:
/* rule 87 can match eol */
YY_RULE_SETUP
#line 186 "tg2.l"
{ BEGIN ss(xTEXT); ytdup(); return(POS); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 187 "tg2.l"
{ BEGIN ss(xTEXT); ytdup(); return(POS); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 188 "tg2.l"
{ BEGIN ss(xS); ytdup(); return(WORDSPEC); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 190 "tg2.l"
{ BEGIN ss(xTEXT); return(xdisc); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 191 "tg2.l"
{ BEGIN ss(xLANG); after_xLANG = xTEXT; return(xdiscl); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 192 "tg2.l"
{ BEGIN ss(xTEXT); yi(BIB); return(BIB); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 193 "tg2.l"
{ BEGIN ss(xTEXT); yi(COLLO); return(COLLO); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 194 "tg2.l"
{ BEGIN ss(xELANG); yi(EQUIV); return(EQUIV); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 195 "tg2.l"
{ BEGIN ss(xTEXT); ytdupn(1); return LANG; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 196 "tg2.l"
{ BEGIN ss(xTEXT); yi(INOTE); return(INOTE); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 197 "tg2.l"
{ BEGIN ss(xTEXT); yi(ISSLP); return(ISSLP); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 198 "tg2.l"
{ BEGIN ss(xTEXT); yi(NOTE); return(NOTE); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 199 "tg2.l"
{ BEGIN ss(xLANG); after_xLANG = xTEXT; return(NOTEL); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 200 "tg2.l"
{ BEGIN ss(xOID); yi(OID); return(OID); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 201 "tg2.l"
{ BEGIN ss(0); ytdup(); return(OIDSPEC); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 202 "tg2.l"
{ BEGIN ss(xTEXT); return(PL_COORD); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 203 "tg2.l"
{ BEGIN ss(xTEXT); return(PL_ID); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 204 "tg2.l"
{ BEGIN ss(xTEXT); yi(PROP); return(PROP); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 206 "tg2.l"
{ BEGIN ss(xINCL); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 207 "tg2.l"
{ includeo(yytext); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 209 "tg2.l"
{ BEGIN ss(xFLUSH); yylloc.file=efile; yylloc.first_line=yylineno; vyyerror(yylloc,"unknown at-command %s\n",yytext, NULL); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 210 "tg2.l"
{ BEGIN ss(0); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 212 "tg2.l"

	YY_BREAK
case 110:
/* rule 110 can match eol */
YY_RULE_SETUP
#line 213 "tg2.l"
{ yycolumn = 1; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(xALLOW):
case YY_STATE_EOF(xB):
case YY_STATE_EOF(xBP):
case YY_STATE_EOF(xBA):
case YY_STATE_EOF(xCF):
case YY_STATE_EOF(xGW):
case YY_STATE_EOF(xPOS):
case YY_STATE_EOF(xSPOS):
case YY_STATE_EOF(xF):
case YY_STATE_EOF(xS):
case YY_STATE_EOF(xSW):
case YY_STATE_EOF(xPROJ):
case YY_STATE_EOF(xLANG):
case YY_STATE_EOF(xTEXT):
case YY_STATE_EOF(xWORD):
case YY_STATE_EOF(xENTSNS):
case YY_STATE_EOF(xWHY):
case YY_STATE_EOF(xCOMMENT):
case YY_STATE_EOF(xELANG):
case YY_STATE_EOF(xOID):
case YY_STATE_EOF(xFLUSH):
case YY_STATE_EOF(xINCL):
#line 215 "tg2.l"
{ if (flextrace) { fprintf(stderr, "<<EOF>>\n"); }
			    if (include_stack_ptr) { includec(); }
			    return(0); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 219 "tg2.l"
ECHO;
	YY_BREAK
#line 2103 "tg2-l.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 414 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 414 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 413);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 219 "tg2.l"


void
alt_wrapup(int clean)
{
  if (clean)
    clean_alt_paren(); 
  dup(b_alt_tok); 
  free(b_alt_tok); 
  b_alt_tok = NULL;
}

static void
basesc(const char *type)
{
  yylloc.file=efile;
  yylloc.first_line=yylineno; 
  vyyerror(yylloc,"misplaced %s semi-colon\n", type, NULL);
}

static void
baseco(const char *type)
{
  yylloc.file=efile;
  yylloc.first_line=yylineno; 
  vyyerror(yylloc,"misplaced %s comma\n", type, NULL);
}

static void
clean_alt_paren(void)
{
  b_alt_tok[strlen(b_alt_tok)-1] = '\0';
}

static char *
unspace(char*s)
{
  int i = strlen(s);
  while (isspace(s[i-1]))
    --i;
  if (i >= 0)
    s[i] = '\0';
  return s;
}

static void
gx_user_action(void)
{
  if (flextrace)
    {
      if (cmt_queue)
	fprintf(stderr, "%s:%d: cmt_queue has %d items\n", efile, yylineno, (int)list_len(cmt_queue));
      fprintf(stderr, "%s:%d: flextrace: state=%s tok=::%s::\n", efile, yylineno, ssnames2[mystate], yytext);
    }
  yylloc.file = efile;
  yylloc.first_line = yylloc.last_line = yylineno;
  yylloc.first_column = yylloc.last_column;
  for(int i = 0; yytext[i] != '\0'; i++)
    {
      if (yytext[i] == '\n')
        {
          yylloc.last_line++;
          yylloc.last_column = 0;
        }
      else 
        {
          yylloc.last_column++;
        }
    }
}

/* include_stack_ptr indexes into include_stack and gives the current
   state.  At the initial state, we push the top-level state into
   include_stack[0] and then the first include is include_stack[1].

   On closing an include, the state pointed to by include_stack_ptr is
   the one we are shutting down.
 */

static void
includeo(char *file)
{
  if ( include_stack_ptr >= MAX_INCLUDE_DEPTH )
    {
      fprintf( stderr, "Includes nested too deeply" );
      exit( 1 );
    }

  if (!include_stack_ptr)
    {
      /* ensure top-level state is saved first on stack */
      include_stack[include_stack_ptr].file = efile;
      include_stack[include_stack_ptr].line = yylineno;
      include_stack[include_stack_ptr].yycb = YY_CURRENT_BUFFER;
      include_stack[include_stack_ptr].fp = yyin;
    }

  ++include_stack_ptr;      

  efile = include_stack[include_stack_ptr].file = (char*)npool_copy((ucp)yytext,curr_cbd->pool);
  include_stack[include_stack_ptr].yycb = YY_CURRENT_BUFFER;
  include_stack[include_stack_ptr].line = yylineno;
  include_stack[include_stack_ptr].fp = yyin = xfopen( yytext, "r" );
  yylineno = 1;

  if (flextrace) { fprintf(stderr, "%s:%d: include switching input to new file\n", efile, yylineno); }
  yy_switch_to_buffer(yy_create_buffer( yyin, YY_BUF_SIZE ) );
  BEGIN(ss(INITIAL));
}

static void
includec(void)
{
  if (include_stack_ptr--)
    {
      fclose(include_stack[include_stack_ptr+1].fp);
      yy_delete_buffer( YY_CURRENT_BUFFER );
      yy_switch_to_buffer(include_stack[include_stack_ptr].yycb);
      efile = include_stack[include_stack_ptr].file;
      yylineno = include_stack[include_stack_ptr].line;
      yyin = include_stack[include_stack_ptr].fp;
      if (flextrace)
        {
          fprintf(stderr, "%s:%d: include of %s complete\n", efile, yylineno,
        	  	           		             include_stack[include_stack_ptr+1].file);
        }
    }
}

void
tg2_l_init(struct iom_io *ip)
{
  if (!ip->use_stdio)
    {
      errmsg_fn = ip->fn;
      efile = (char*)ip->fn;
      if ((ip->fp = xfopen(efile, "r")))
	yyrestart(ip->fp);
    }
}
void
tg2_l_term(void)
{
  
}

