#ifndef NULL
#define NULL (char *)0
#endif
#include "xnn.h"
#include "xtf.h"
struct xnn_nstab xtf_nstab[] = {
  { xtf_n__, "xmlns", "http://oracc.org/ns/xtf/1.0" },
  { xtf_n_g, "xmlns:g", "http://oracc.org/ns/gdl/1.0" },
  { xtf_n_n, "xmlns:n", "http://oracc.org/ns/norm/1.0" },
  { xtf_n_note, "xmlns:note", "http://oracc.org/ns/note/1.0" },
  { xtf_n_syn, "xmlns:syn", "http://oracc.org/ns/syntax/1.0" },
  { xtf_n_xh, "xmlns:xh", "http://www.w3.org/1999/xhtml" },
  { xtf_n_xtr, "xmlns:xtr", "http://oracc.org/ns/xtr/1.0" },
  { xtf_a_enum_top, NULL, NULL },
};

struct xnn_xname xtf_anames[] =
{
  { "xmlns:g", "xmlns:g" },
  { "xmlns:n", "xmlns:n" },
  { "xmlns:note", "xmlns:note" },
  { "xmlns:syn", "xmlns:syn" },
  { "xmlns:xh", "xmlns:xh" },
  { "xmlns:xml", "xmlns:xml" },
  { "xmlns:xtr", "xmlns:xtr" },
  { "alt", "alt" },
  { "base", "base" },
  { "class", "class" },
  { "cols", "cols" },
  { "contrefs", "contrefs" },
  { "dir", "dir" },
  { "endflag", "endflag" },
  { "ex_label", "ex_label" },
  { "extent", "extent" },
  { "flags", "flags" },
  { "form", "form" },
  { "fragid", "fragid" },
  { "from", "from" },
  { "fwhost", "fwhost" },
  { "g:accented", "http://oracc.org/ns/gdl/1.0:accented" },
  { "g:break", "http://oracc.org/ns/gdl/1.0:break" },
  { "g:breakEnd", "http://oracc.org/ns/gdl/1.0:breakEnd" },
  { "g:breakStart", "http://oracc.org/ns/gdl/1.0:breakStart" },
  { "g:c", "http://oracc.org/ns/gdl/1.0:c" },
  { "g:collated", "http://oracc.org/ns/gdl/1.0:collated" },
  { "g:damageEnd", "http://oracc.org/ns/gdl/1.0:damageEnd" },
  { "g:damageStart", "http://oracc.org/ns/gdl/1.0:damageStart" },
  { "g:delim", "http://oracc.org/ns/gdl/1.0:delim" },
  { "g:em", "http://oracc.org/ns/gdl/1.0:em" },
  { "g:hc", "http://oracc.org/ns/gdl/1.0:hc" },
  { "g:ho", "http://oracc.org/ns/gdl/1.0:ho" },
  { "g:logolang", "http://oracc.org/ns/gdl/1.0:logolang" },
  { "g:o", "http://oracc.org/ns/gdl/1.0:o" },
  { "g:pos", "http://oracc.org/ns/gdl/1.0:pos" },
  { "g:prox", "http://oracc.org/ns/gdl/1.0:prox" },
  { "g:queried", "http://oracc.org/ns/gdl/1.0:queried" },
  { "g:remarked", "http://oracc.org/ns/gdl/1.0:remarked" },
  { "g:role", "http://oracc.org/ns/gdl/1.0:role" },
  { "g:script", "http://oracc.org/ns/gdl/1.0:script" },
  { "g:sign", "http://oracc.org/ns/gdl/1.0:sign" },
  { "g:status", "http://oracc.org/ns/gdl/1.0:status" },
  { "g:statusEnd", "http://oracc.org/ns/gdl/1.0:statusEnd" },
  { "g:statusStart", "http://oracc.org/ns/gdl/1.0:statusStart" },
  { "g:surroEnd", "http://oracc.org/ns/gdl/1.0:surroEnd" },
  { "g:surroStart", "http://oracc.org/ns/gdl/1.0:surroStart" },
  { "g:type", "http://oracc.org/ns/gdl/1.0:type" },
  { "g:uflag1", "http://oracc.org/ns/gdl/1.0:uflag1" },
  { "g:uflag2", "http://oracc.org/ns/gdl/1.0:uflag2" },
  { "g:uflag3", "http://oracc.org/ns/gdl/1.0:uflag3" },
  { "g:uflag4", "http://oracc.org/ns/gdl/1.0:uflag4" },
  { "g:utf8", "http://oracc.org/ns/gdl/1.0:utf8" },
  { "g:varc", "http://oracc.org/ns/gdl/1.0:varc" },
  { "g:vari", "http://oracc.org/ns/gdl/1.0:vari" },
  { "g:varo", "http://oracc.org/ns/gdl/1.0:varo" },
  { "guide", "guide" },
  { "hand", "hand" },
  { "haslinks", "haslinks" },
  { "headform", "headform" },
  { "headref", "headref" },
  { "hlid", "hlid" },
  { "implicit", "implicit" },
  { "kkey", "kkey" },
  { "l", "l" },
  { "label", "label" },
  { "lang", "lang" },
  { "lemma", "lemma" },
  { "level", "level" },
  { "lid", "lid" },
  { "morph", "morph" },
  { "n", "n" },
  { "n:num", "http://oracc.org/ns/norm/1.0:num" },
  { "norm", "norm" },
  { "note:auto", "http://oracc.org/ns/note/1.0:auto" },
  { "note:label", "http://oracc.org/ns/note/1.0:label" },
  { "note:mark", "http://oracc.org/ns/note/1.0:mark" },
  { "note:ref", "http://oracc.org/ns/note/1.0:ref" },
  { "o", "o" },
  { "p", "p" },
  { "place", "place" },
  { "plid", "plid" },
  { "pos", "pos" },
  { "primes", "primes" },
  { "project", "project" },
  { "ref", "ref" },
  { "scid", "scid" },
  { "scope", "scope" },
  { "score-mode", "score-mode" },
  { "score-type", "score-type" },
  { "score-word", "score-word" },
  { "sense", "sense" },
  { "sexified", "sexified" },
  { "sigref", "sigref" },
  { "silent", "silent" },
  { "span", "span" },
  { "spanall", "spanall" },
  { "state", "state" },
  { "strict", "strict" },
  { "subtype", "subtype" },
  { "swc-final", "swc-final" },
  { "syn:brk-after", "http://oracc.org/ns/syntax/1.0:brk-after" },
  { "syn:brk-before", "http://oracc.org/ns/syntax/1.0:brk-before" },
  { "syn:ub-after", "http://oracc.org/ns/syntax/1.0:ub-after" },
  { "syn:ub-before", "http://oracc.org/ns/syntax/1.0:ub-before" },
  { "targ-id", "targ-id" },
  { "targ-n", "targ-n" },
  { "tid", "tid" },
  { "to", "to" },
  { "type", "type" },
  { "unit", "unit" },
  { "url", "url" },
  { "varnum", "varnum" },
  { "xml:id", "http://www.w3.org/XML/1998/namespace:id" },
  { "xml:lang", "http://www.w3.org/XML/1998/namespace:lang" },
  { "xtr:cid", "http://oracc.org/ns/xtr/1.0:cid" },
  { "xtr:code", "http://oracc.org/ns/xtr/1.0:code" },
  { "xtr:cols", "http://oracc.org/ns/xtr/1.0:cols" },
  { "xtr:disamb", "http://oracc.org/ns/xtr/1.0:disamb" },
  { "xtr:eref", "http://oracc.org/ns/xtr/1.0:eref" },
  { "xtr:form", "http://oracc.org/ns/xtr/1.0:form" },
  { "xtr:hdr-ref", "http://oracc.org/ns/xtr/1.0:hdr-ref" },
  { "xtr:lab-end-label", "http://oracc.org/ns/xtr/1.0:lab-end-label" },
  { "xtr:lab-end-lnum", "http://oracc.org/ns/xtr/1.0:lab-end-lnum" },
  { "xtr:lab-start-label", "http://oracc.org/ns/xtr/1.0:lab-start-label" },
  { "xtr:lab-start-lnum", "http://oracc.org/ns/xtr/1.0:lab-start-lnum" },
  { "xtr:label", "http://oracc.org/ns/xtr/1.0:label" },
  { "xtr:lem", "http://oracc.org/ns/xtr/1.0:lem" },
  { "xtr:nrefs", "http://oracc.org/ns/xtr/1.0:nrefs" },
  { "xtr:overlap", "http://oracc.org/ns/xtr/1.0:overlap" },
  { "xtr:ref", "http://oracc.org/ns/xtr/1.0:ref" },
  { "xtr:refs", "http://oracc.org/ns/xtr/1.0:refs" },
  { "xtr:rend-label", "http://oracc.org/ns/xtr/1.0:rend-label" },
  { "xtr:rows", "http://oracc.org/ns/xtr/1.0:rows" },
  { "xtr:se_label", "http://oracc.org/ns/xtr/1.0:se_label" },
  { "xtr:silent", "http://oracc.org/ns/xtr/1.0:silent" },
  { "xtr:span", "http://oracc.org/ns/xtr/1.0:span" },
  { "xtr:spanall", "http://oracc.org/ns/xtr/1.0:spanall" },
  { "xtr:sref", "http://oracc.org/ns/xtr/1.0:sref" },
  { "xtr:standalone", "http://oracc.org/ns/xtr/1.0:standalone" },
  { "xtr:type", "http://oracc.org/ns/xtr/1.0:type" },
  { "xtr:unit", "http://oracc.org/ns/xtr/1.0:unit" },
  { "xtr:uref", "http://oracc.org/ns/xtr/1.0:uref" },
  { NULL, NULL },
};
struct xnn_attr xtf_abases[] =
{
  { { "alt",NULL } , { "alt",NULL } },
  { { "base",NULL } , { "base",NULL } },
  { { "class",NULL } , { "class",NULL } },
  { { "cols",NULL } , { "cols",NULL } },
  { { "contrefs",NULL } , { "contrefs",NULL } },
  { { "dir",NULL } , { "dir",NULL } },
  { { "endflag",NULL } , { "endflag",NULL } },
  { { "ex_label",NULL } , { "ex_label",NULL } },
  { { "extent",NULL } , { "extent",NULL } },
  { { "flags",NULL } , { "flags",NULL } },
  { { "form",NULL } , { "form",NULL } },
  { { "fragid",NULL } , { "fragid",NULL } },
  { { "from",NULL } , { "from",NULL } },
  { { "fwhost",NULL } , { "fwhost",NULL } },
  { { "g:accented",NULL } , { "http://oracc.org/ns/gdl/1.0:accented",NULL } },
  { { "g:break",NULL } , { "http://oracc.org/ns/gdl/1.0:break",NULL } },
  { { "g:breakEnd",NULL } , { "http://oracc.org/ns/gdl/1.0:breakEnd",NULL } },
  { { "g:breakStart",NULL } , { "http://oracc.org/ns/gdl/1.0:breakStart",NULL } },
  { { "g:c",NULL } , { "http://oracc.org/ns/gdl/1.0:c",NULL } },
  { { "g:collated",NULL } , { "http://oracc.org/ns/gdl/1.0:collated",NULL } },
  { { "g:damageEnd",NULL } , { "http://oracc.org/ns/gdl/1.0:damageEnd",NULL } },
  { { "g:damageStart",NULL } , { "http://oracc.org/ns/gdl/1.0:damageStart",NULL } },
  { { "g:delim",NULL } , { "http://oracc.org/ns/gdl/1.0:delim",NULL } },
  { { "g:em",NULL } , { "http://oracc.org/ns/gdl/1.0:em",NULL } },
  { { "g:hc",NULL } , { "http://oracc.org/ns/gdl/1.0:hc",NULL } },
  { { "g:ho",NULL } , { "http://oracc.org/ns/gdl/1.0:ho",NULL } },
  { { "g:logolang",NULL } , { "http://oracc.org/ns/gdl/1.0:logolang",NULL } },
  { { "g:o",NULL } , { "http://oracc.org/ns/gdl/1.0:o",NULL } },
  { { "g:pos",NULL } , { "http://oracc.org/ns/gdl/1.0:pos",NULL } },
  { { "g:prox",NULL } , { "http://oracc.org/ns/gdl/1.0:prox",NULL } },
  { { "g:queried",NULL } , { "http://oracc.org/ns/gdl/1.0:queried",NULL } },
  { { "g:remarked",NULL } , { "http://oracc.org/ns/gdl/1.0:remarked",NULL } },
  { { "g:role",NULL } , { "http://oracc.org/ns/gdl/1.0:role",NULL } },
  { { "g:script",NULL } , { "http://oracc.org/ns/gdl/1.0:script",NULL } },
  { { "g:sign",NULL } , { "http://oracc.org/ns/gdl/1.0:sign",NULL } },
  { { "g:status",NULL } , { "http://oracc.org/ns/gdl/1.0:status",NULL } },
  { { "g:statusEnd",NULL } , { "http://oracc.org/ns/gdl/1.0:statusEnd",NULL } },
  { { "g:statusStart",NULL } , { "http://oracc.org/ns/gdl/1.0:statusStart",NULL } },
  { { "g:surroEnd",NULL } , { "http://oracc.org/ns/gdl/1.0:surroEnd",NULL } },
  { { "g:surroStart",NULL } , { "http://oracc.org/ns/gdl/1.0:surroStart",NULL } },
  { { "g:type",NULL } , { "http://oracc.org/ns/gdl/1.0:type",NULL } },
  { { "g:uflag1",NULL } , { "http://oracc.org/ns/gdl/1.0:uflag1",NULL } },
  { { "g:uflag2",NULL } , { "http://oracc.org/ns/gdl/1.0:uflag2",NULL } },
  { { "g:uflag3",NULL } , { "http://oracc.org/ns/gdl/1.0:uflag3",NULL } },
  { { "g:uflag4",NULL } , { "http://oracc.org/ns/gdl/1.0:uflag4",NULL } },
  { { "g:utf8",NULL } , { "http://oracc.org/ns/gdl/1.0:utf8",NULL } },
  { { "g:varc",NULL } , { "http://oracc.org/ns/gdl/1.0:varc",NULL } },
  { { "g:vari",NULL } , { "http://oracc.org/ns/gdl/1.0:vari",NULL } },
  { { "g:varo",NULL } , { "http://oracc.org/ns/gdl/1.0:varo",NULL } },
  { { "guide",NULL } , { "guide",NULL } },
  { { "hand",NULL } , { "hand",NULL } },
  { { "haslinks",NULL } , { "haslinks",NULL } },
  { { "headform",NULL } , { "headform",NULL } },
  { { "headref",NULL } , { "headref",NULL } },
  { { "hlid",NULL } , { "hlid",NULL } },
  { { "implicit",NULL } , { "implicit",NULL } },
  { { "kkey",NULL } , { "kkey",NULL } },
  { { "l",NULL } , { "l",NULL } },
  { { "label",NULL } , { "label",NULL } },
  { { "lang",NULL } , { "lang",NULL } },
  { { "lemma",NULL } , { "lemma",NULL } },
  { { "level",NULL } , { "level",NULL } },
  { { "lid",NULL } , { "lid",NULL } },
  { { "morph",NULL } , { "morph",NULL } },
  { { "n",NULL } , { "n",NULL } },
  { { "n:num",NULL } , { "http://oracc.org/ns/norm/1.0:num",NULL } },
  { { "norm",NULL } , { "norm",NULL } },
  { { "note:auto",NULL } , { "http://oracc.org/ns/note/1.0:auto",NULL } },
  { { "note:label",NULL } , { "http://oracc.org/ns/note/1.0:label",NULL } },
  { { "note:mark",NULL } , { "http://oracc.org/ns/note/1.0:mark",NULL } },
  { { "note:ref",NULL } , { "http://oracc.org/ns/note/1.0:ref",NULL } },
  { { "o",NULL } , { "o",NULL } },
  { { "p",NULL } , { "p",NULL } },
  { { "place",NULL } , { "place",NULL } },
  { { "plid",NULL } , { "plid",NULL } },
  { { "pos",NULL } , { "pos",NULL } },
  { { "primes",NULL } , { "primes",NULL } },
  { { "project",NULL } , { "project",NULL } },
  { { "ref",NULL } , { "ref",NULL } },
  { { "scid",NULL } , { "scid",NULL } },
  { { "scope",NULL } , { "scope",NULL } },
  { { "score-mode",NULL } , { "score-mode",NULL } },
  { { "score-type",NULL } , { "score-type",NULL } },
  { { "score-word",NULL } , { "score-word",NULL } },
  { { "sense",NULL } , { "sense",NULL } },
  { { "sexified",NULL } , { "sexified",NULL } },
  { { "sigref",NULL } , { "sigref",NULL } },
  { { "silent",NULL } , { "silent",NULL } },
  { { "span",NULL } , { "span",NULL } },
  { { "spanall",NULL } , { "spanall",NULL } },
  { { "state",NULL } , { "state",NULL } },
  { { "strict",NULL } , { "strict",NULL } },
  { { "subtype",NULL } , { "subtype",NULL } },
  { { "swc-final",NULL } , { "swc-final",NULL } },
  { { "syn:brk-after",NULL } , { "http://oracc.org/ns/syntax/1.0:brk-after",NULL } },
  { { "syn:brk-before",NULL } , { "http://oracc.org/ns/syntax/1.0:brk-before",NULL } },
  { { "syn:ub-after",NULL } , { "http://oracc.org/ns/syntax/1.0:ub-after",NULL } },
  { { "syn:ub-before",NULL } , { "http://oracc.org/ns/syntax/1.0:ub-before",NULL } },
  { { "targ-id",NULL } , { "targ-id",NULL } },
  { { "targ-n",NULL } , { "targ-n",NULL } },
  { { "tid",NULL } , { "tid",NULL } },
  { { "to",NULL } , { "to",NULL } },
  { { "type",NULL } , { "type",NULL } },
  { { "unit",NULL } , { "unit",NULL } },
  { { "url",NULL } , { "url",NULL } },
  { { "varnum",NULL } , { "varnum",NULL } },
  { { "xml:id",NULL } , { "http://www.w3.org/XML/1998/namespace:id",NULL } },
  { { "xml:lang",NULL } , { "http://www.w3.org/XML/1998/namespace:lang",NULL } },
  { { "xtr:cid",NULL } , { "http://oracc.org/ns/xtr/1.0:cid",NULL } },
  { { "xtr:code",NULL } , { "http://oracc.org/ns/xtr/1.0:code",NULL } },
  { { "xtr:cols",NULL } , { "http://oracc.org/ns/xtr/1.0:cols",NULL } },
  { { "xtr:disamb",NULL } , { "http://oracc.org/ns/xtr/1.0:disamb",NULL } },
  { { "xtr:eref",NULL } , { "http://oracc.org/ns/xtr/1.0:eref",NULL } },
  { { "xtr:form",NULL } , { "http://oracc.org/ns/xtr/1.0:form",NULL } },
  { { "xtr:hdr-ref",NULL } , { "http://oracc.org/ns/xtr/1.0:hdr-ref",NULL } },
  { { "xtr:lab-end-label",NULL } , { "http://oracc.org/ns/xtr/1.0:lab-end-label",NULL } },
  { { "xtr:lab-end-lnum",NULL } , { "http://oracc.org/ns/xtr/1.0:lab-end-lnum",NULL } },
  { { "xtr:lab-start-label",NULL } , { "http://oracc.org/ns/xtr/1.0:lab-start-label",NULL } },
  { { "xtr:lab-start-lnum",NULL } , { "http://oracc.org/ns/xtr/1.0:lab-start-lnum",NULL } },
  { { "xtr:label",NULL } , { "http://oracc.org/ns/xtr/1.0:label",NULL } },
  { { "xtr:lem",NULL } , { "http://oracc.org/ns/xtr/1.0:lem",NULL } },
  { { "xtr:nrefs",NULL } , { "http://oracc.org/ns/xtr/1.0:nrefs",NULL } },
  { { "xtr:overlap",NULL } , { "http://oracc.org/ns/xtr/1.0:overlap",NULL } },
  { { "xtr:ref",NULL } , { "http://oracc.org/ns/xtr/1.0:ref",NULL } },
  { { "xtr:refs",NULL } , { "http://oracc.org/ns/xtr/1.0:refs",NULL } },
  { { "xtr:rend-label",NULL } , { "http://oracc.org/ns/xtr/1.0:rend-label",NULL } },
  { { "xtr:rows",NULL } , { "http://oracc.org/ns/xtr/1.0:rows",NULL } },
  { { "xtr:se_label",NULL } , { "http://oracc.org/ns/xtr/1.0:se_label",NULL } },
  { { "xtr:silent",NULL } , { "http://oracc.org/ns/xtr/1.0:silent",NULL } },
  { { "xtr:span",NULL } , { "http://oracc.org/ns/xtr/1.0:span",NULL } },
  { { "xtr:spanall",NULL } , { "http://oracc.org/ns/xtr/1.0:spanall",NULL } },
  { { "xtr:sref",NULL } , { "http://oracc.org/ns/xtr/1.0:sref",NULL } },
  { { "xtr:standalone",NULL } , { "http://oracc.org/ns/xtr/1.0:standalone",NULL } },
  { { "xtr:type",NULL } , { "http://oracc.org/ns/xtr/1.0:type",NULL } },
  { { "xtr:unit",NULL } , { "http://oracc.org/ns/xtr/1.0:unit",NULL } },
  { { "xtr:uref",NULL } , { "http://oracc.org/ns/xtr/1.0:uref",NULL } },
  { { NULL,NULL } , { NULL,NULL } },
};
struct xnn_xname xtf_enames[] =
{
  { "ag", "http://oracc.org/ns/xtf/1.0:ag" },
  { "atf", "http://oracc.org/ns/xtf/1.0:atf" },
  { "c", "http://oracc.org/ns/xtf/1.0:c" },
  { "cmt", "http://oracc.org/ns/xtf/1.0:cmt" },
  { "column", "http://oracc.org/ns/xtf/1.0:column" },
  { "composite", "http://oracc.org/ns/xtf/1.0:composite" },
  { "div", "http://oracc.org/ns/xtf/1.0:div" },
  { "e", "http://oracc.org/ns/xtf/1.0:e" },
  { "eg", "http://oracc.org/ns/xtf/1.0:eg" },
  { "f", "http://oracc.org/ns/xtf/1.0:f" },
  { "g:a", "http://oracc.org/ns/gdl/1.0:a" },
  { "g:b", "http://oracc.org/ns/gdl/1.0:b" },
  { "g:c", "http://oracc.org/ns/gdl/1.0:c" },
  { "g:d", "http://oracc.org/ns/gdl/1.0:d" },
  { "g:f", "http://oracc.org/ns/gdl/1.0:f" },
  { "g:g", "http://oracc.org/ns/gdl/1.0:g" },
  { "g:gg", "http://oracc.org/ns/gdl/1.0:gg" },
  { "g:gloss", "http://oracc.org/ns/gdl/1.0:gloss" },
  { "g:m", "http://oracc.org/ns/gdl/1.0:m" },
  { "g:n", "http://oracc.org/ns/gdl/1.0:n" },
  { "g:nonw", "http://oracc.org/ns/gdl/1.0:nonw" },
  { "g:o", "http://oracc.org/ns/gdl/1.0:o" },
  { "g:p", "http://oracc.org/ns/gdl/1.0:p" },
  { "g:q", "http://oracc.org/ns/gdl/1.0:q" },
  { "g:r", "http://oracc.org/ns/gdl/1.0:r" },
  { "g:s", "http://oracc.org/ns/gdl/1.0:s" },
  { "g:surro", "http://oracc.org/ns/gdl/1.0:surro" },
  { "g:swc", "http://oracc.org/ns/gdl/1.0:swc" },
  { "g:v", "http://oracc.org/ns/gdl/1.0:v" },
  { "g:w", "http://oracc.org/ns/gdl/1.0:w" },
  { "g:x", "http://oracc.org/ns/gdl/1.0:x" },
  { "h", "http://oracc.org/ns/xtf/1.0:h" },
  { "include", "http://oracc.org/ns/xtf/1.0:include" },
  { "l", "http://oracc.org/ns/xtf/1.0:l" },
  { "lg", "http://oracc.org/ns/xtf/1.0:lg" },
  { "m", "http://oracc.org/ns/xtf/1.0:m" },
  { "n:g", "http://oracc.org/ns/norm/1.0:g" },
  { "n:grouped-word", "http://oracc.org/ns/norm/1.0:grouped-word" },
  { "n:s", "http://oracc.org/ns/norm/1.0:s" },
  { "n:w", "http://oracc.org/ns/norm/1.0:w" },
  { "n:word-group", "http://oracc.org/ns/norm/1.0:word-group" },
  { "nong", "http://oracc.org/ns/xtf/1.0:nong" },
  { "nonl", "http://oracc.org/ns/xtf/1.0:nonl" },
  { "nonx", "http://oracc.org/ns/xtf/1.0:nonx" },
  { "note:link", "http://oracc.org/ns/note/1.0:link" },
  { "note:text", "http://oracc.org/ns/note/1.0:text" },
  { "object", "http://oracc.org/ns/xtf/1.0:object" },
  { "protocol", "http://oracc.org/ns/xtf/1.0:protocol" },
  { "protocols", "http://oracc.org/ns/xtf/1.0:protocols" },
  { "referto", "http://oracc.org/ns/xtf/1.0:referto" },
  { "score", "http://oracc.org/ns/xtf/1.0:score" },
  { "sealing", "http://oracc.org/ns/xtf/1.0:sealing" },
  { "sigdef", "http://oracc.org/ns/xtf/1.0:sigdef" },
  { "surface", "http://oracc.org/ns/xtf/1.0:surface" },
  { "surro", "http://oracc.org/ns/xtf/1.0:surro" },
  { "synopticon", "http://oracc.org/ns/xtf/1.0:synopticon" },
  { "transliteration", "http://oracc.org/ns/xtf/1.0:transliteration" },
  { "v", "http://oracc.org/ns/xtf/1.0:v" },
  { "variant", "http://oracc.org/ns/xtf/1.0:variant" },
  { "variants", "http://oracc.org/ns/xtf/1.0:variants" },
  { "xh:div", "http://www.w3.org/1999/xhtml:div" },
  { "xh:h1", "http://www.w3.org/1999/xhtml:h1" },
  { "xh:h2", "http://www.w3.org/1999/xhtml:h2" },
  { "xh:h3", "http://www.w3.org/1999/xhtml:h3" },
  { "xh:innerp", "http://www.w3.org/1999/xhtml:innerp" },
  { "xh:p", "http://www.w3.org/1999/xhtml:p" },
  { "xh:span", "http://www.w3.org/1999/xhtml:span" },
  { "xtf", "http://oracc.org/ns/xtf/1.0:xtf" },
  { "xtr:l2t", "http://oracc.org/ns/xtr/1.0:l2t" },
  { "xtr:map", "http://oracc.org/ns/xtr/1.0:map" },
  { "xtr:translation", "http://oracc.org/ns/xtr/1.0:translation" },
  { NULL, NULL },
};
struct xnn_data xtf_data = { xtf_enames, xtf_anames, xtf_nstab };
